depromeet/ygtang-client

src/components/common/Tag.tsx
src/components/home/ContentHeader.tsx
src/components/home/ContentThumbnail.tsx
src/components/home/ContentView.tsx
src/pages/_app.tsx
src/pages/index.tsx
src/styles/GlobalStyle/GlobalStyle.tsx
src/styles/GlobalStyle/reset.ts
src/styles/Theme/Theme.ts

#31 
아직 디자인 미완성이지만, `globalStyle`에 수정이 있어서 풀리퀘 올립니다.
- 피그마 와이어프레임 단계라 theme을 크게 수정하지는 않았어요. 나중에 디자인 컨셉 나오게 되면 다시 theme에 font-size, font-weight, color 추가해서 적용하면 될 것 같아요 :)
- <ContentThumbnail /> 반복적으로 하드 코딩 된 부분은 백엔드 분이랑 이야기 후에 목데이터로 변경해서 map 돌리는 방식으로 수정해놓겠습니다!
- globalStyle에 reset을 넣어놨어요. 평소에 하던 방식이긴 한데.. 다른 분들은 어떻게 하시나 궁금하네요 :) 수정 필요하다면 말씀해주세요!
- [레퍼런스](https://meyerweb.com/eric/tools/css/reset/)
- 전체 body에 드래그 방지를 넣어놨는데, 클래스명으로 'draggable'을 주어 선택적으로 드래그하도록 했어요
- 외려 반대로 드래그 자유도를 주되 제한된 부분에서만 드래그 방지하는 방법으로 변경 해야되나 고민이 되는데 이후 디자인 보면서 수정해도 될 것 같아요.
```css
body {
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
.draggable {
-webkit-user-select: all;
-moz-user-select: all;
-ms-user-select: all;
user-select: all;
}
}
```
- [reset …

영감 보기 그리드 디자인 설정

---

.editorconfig
@types/global.d.ts
src/hooks/bridge/useAppMessage/AppMessageListener.tsx
src/hooks/bridge/useAppMessage/index.ts
src/hooks/bridge/useAppMessage/useAppMessage.ts
tsconfig.json

> 이슈 브랜치 이름이 `issue/50` 으로 되어 있는데, 훅 제작은 분기를 해야할 것 같아서 분리하였어요!
> 실제 이슈는 #52 입니다!!
- [EditorConfig](https://editorconfig.org/) 파일 추가
- bridge 폴더 아래에 훅들 추가 ***<< bridge 폴더 명이 애매할 수도 있을 것 같아서 제안해주시면 좋을 것 같아요~!!***
- 메인 message 핸들링 담당하는 `useAppMessage` 추가
- useAppMessage을 담당하는 AppMessageListener 컴포넌트 생성
useAppMessage를 어디서 사용해야할지 고민이긴 한데... 생각해 본 방법은 다음과 같아요
1. 전역 _app.tsx에서 핸들링 후 store를 사용하여 각 페이지로 데이터 보내기
2. 각 페이지에서 AppMessage 리스닝 후 처리 (useAppMessage에 actions을 주입하는 방향으로 가면 좋을듯) (이거 생각중이긴 해요)

app to web 테스트용 웹 사이트 개발 - useAppMessage 훅 개발

---

src/constants/motions.ts

`framer-motion` 사용 시 제가 사용하던 상수들을 예제로써 적용해보았어요.
```tsx
import { defaultFadeInUpVariants } from "~/constants/motions";
<motion.div
initial="initial"
animate="animate"
exit="exit"
variants={defaultFadeInUpVariants}
>
</motion.div>
```
애니메이션에 대한 상수 값들이 컴포넌트에 위치하는 경우, 가독성을 떨어트릴 수도 있다고 생각해서 작업내용처럼 상수들을 모아서 관리하고 위 방법처럼 import하여 사용하곤 했어요!
`staggerOne`, `staggerHalf`의 경우 [해당 예제](https://codesandbox.io/s/framer-motion-side-menu-mx2rw?from-embed)처럼 각 child들의 애니메이션에 딜레이를 줄 때 사용해서 추가해보았어요!
사용하지 않는 방향이 된다면 추후 지워보면 될 거 같아용
- [framer motion 공식 문서](https://www.framer.com/docs/)
- [framer motion staggerChildren](https://www.framer.com/docs/transition/###staggerchildren)
- [framer motion staggerChildren Example](https://codesandbox.io/s/framer-motion-side-menu-mx2rw?from-embed)

Framer motion 상수 설정

---

src/pages/_document.tsx
src/styles/GlobalStyle/GlobalStyle.tsx
src/styles/GlobalStyle/reset.ts

`_document`에 `link` 태그를 이용해 `Pretendard` 폰트를 적용했어용
css `:root`에 `font-family` 설정 하였으나, `reset`에서 여러 태그들의 font-family를 inherit으로 설정하지 않고 있어 `*` 선택자에 추가하였슴니당
저는 기존에 `html link`보다는 `css @import`를 이용해서 사용하곤 했는데,
이번에 궁금해서 성능적으로 어떤 것이 우위에 있을 지 궁금해서 찾아봤어요!
> 유의미하진 않지만, `html link`가 이점이 있다고 합니다 ...!
- [Best way to add a custom font to my site?](https://webmasters.stackexchange.com/questions/108916/best-way-to-add-a-custom-font-to-my-site)
- [dont use @import](https://www.stevesouders.com/blog/2009/04/09/dont-use-import/)

Pretendard 폰트 적용

---

src/components/common/ModalWrapper.tsx
src/components/common/PortalWrapper.tsx
src/hooks/common/useToggle.ts

모달 사용 시, `Wrapper`로써 portal 컴포넌트를 개발했어요.
추가적으로 `Wrapper` 컴포넌트에 `isShowing`이라는 이름으로 렌더링 여부를 결정했기 때문에,
`useModal`이라는 이름의 hook 보다는 `useToggle` 형태로 조금 더 범용적으로 쓰일 수 있도록 개발해보았어요.
> 추가적으로 `AnimatePresence` 컴포넌트를 사용해서 `framer`를 사용한 modal이 `exit`할 때도 애니메이션이 재생될 수 있도록 개발했어요.
- ### ModalWrapper
```tsx
import ModalWrapper from '~/components/common/ModalWrapper';
<ModalWrapper isShowing={어떤state}>
<어떤모달컴포넌트라던가JSX />
</ModalWrapper>
```
- ### useToggle
```tsx
import useToggle from '~/hooks/common/useToggle';
// const [상태, 토글함수] = useToggle(초기값);
const [isShowing, toggleIsShowing] = useToggle(false);
```
- ### 합쳐서
```tsx
import ModalWrapper from '~/components/common/ModalWrapper';
import useToggle from '~/hooks/common/useToggle';
function Test() {
const [isShowing, toggleIsShowing] = useToggle(false); …
```

모달 관련 컴포넌트 및 훅 개발

---

src/components/home/ContentHeader.tsx
src/components/home/ContentThumbnail.tsx
src/styles/GlobalStyle/GlobalStyle.tsx
src/styles/Theme/Theme.ts

emotion color를 적용했습니다. 
네이밍은 디자인 시스템에 선언된 그대로를 가져갔습니다.
한 가지 걸리는 점은 `primary_disabled` 이 친구 입니다. 따로 어떻게 정의할까 많이 고민하다가 사용 목적에 맞도록 적용하는 것이 가장 좋다고 생각되어 해당 방식으로 적용했습니다.(레퍼런스 1 참조)
처음에 색을 선언할때 `gey1`과 같이하려다가 추후에 디자이너분들이 계속 `gey01`로 사용될것으로 예상되어 그대로를 입력했습니다.
```tsx
const HeaderButtonCss = (theme: Theme) => css`
width: 32px;
height: 32px;
background: ${theme.color.background};
font-weight: 700;
font-size: 10px;
`;
```
1. https://zeroheight.com/blog/naming-conventions-for-your-design-system/

emotion color palette 설정

---

jest.config.js
src/__test__/utils/customRender.tsx
src/__test__/utils/index.ts
src/components/common/NavigationBar/NavigationBar.test.tsx
src/components/common/NavigationBar/NavigationBar.tsx
src/components/common/NavigationBar/index.test.tsx
src/components/common/NavigationBar/index.tsx
src/pages/test/index.tsx

`NavigationBar` 컴포넌트를 개발했어요
framer 상, `2-depth ~` 부분을 컴포넌트화 했어요.
> 다른 NavigationBar의 경우 Main view만 있기 때문에 모듈화하지 않는 게 좋을 거 같았어용
구현체의 왼쪽 back 버튼의 경우 링크가 있을 시 해당 링크로, 없을 시 `back` 하도록 개발하였고
오른쪽 버튼 구역의 경우 `ReactElement`를 props로 받도록 했슴다
> `_app` 에서 컴포넌트를 그린 후, 전역 상태라던지 라우트별 오브젝트를 맵핑해서 관리할까도 생각해봤는데 더 유지보수에 어려운 방법이지 않을까... 라는 생각으로 이렇게 개발해봤어요 🥲 
```jsx
import NavigationBar from '~/components/common/NavigationBar';
// 모든 props 주입 시
<NavigationBar backLink="/" title="Title" rightElement={<IconButton iconName="DeleteIcon" light />} />
// router.back 실행을 위해서는
<NavigationBar title="Title" rightElement={<IconButton iconName="DeleteIcon" light />} />
// router.back + 아무것도 없이
<NavigationBar  />
```
테스트 코드에 대한 부분이지만, 현재 css prop를 **jest 환경**에서 Invalid하게 인식함(warning)과 동시에 스타일이 적용되지 않는 이슈가 있어요.
서치를 해본 결과 [해당 …

NavigationBar 컴포넌트 개발

---

src/components/common/Tag.tsx

- 기존의 28px -> 24px로 높이 변경되었습니다.
- API 연결 전에 Tag를 들어올것을 예상하고 작성을 해보았습니다.
- Props 이름을 변경했습니다.
- ThumbnailTag의 마지막 요소에 대한 사용 변경을 했습니다.
- 마지막요소에 넣는것보다 사용하는쪽에서 넣어주는게 어떨까해서 변경해보았습니다.
```tsx
<Tag tag={{ id: 0, content: '하이' }} />
<Tag deletable tag={{ id: 0, content: '하이' }} />
```
```tsx
<div css={contentTagsCss}>
<ThumbnailTag text="영감" />
<ThumbnailTag text="UX/UI" />
<ThumbnailTag text="브랜드 디자인 레퍼런스 모음집" />
<ThumbnailTag text="디자인인사이트" />
</div>
const contentTagsCss = css`
//(...생략)
padding-right: 16px;
`;
```

ThumbnailTag, Tag 디자인 추가 및 변경 #92

---

src/components/common/CheckList.tsx
src/pages/test/index.tsx

- 리뷰 내용에 따라 기존의 id를 Props로 주입받는 형태가 아닌 내부에서 유니크한 id를 생성해서 사용한것으로 Refactor하였습니다.
```
id의 경우에는 굳이 외부 주입 받지 않더라도 useId 등으로 컴포넌트 안에서 생성해 줄 수 있을 것 같아요!
(다만 react 18 요소 사용을 위한 패치인 https://github.com/depromeet/11th_7team_web/pull/87 피알이 머지되지 않아서, 추후에 TODO 이슈로 만들어두는게 좋을 것 같네요)
관련 링크: https://github.com/depromeet/11th_7team_web/pull/86#discussion_r862462220
```
- 잘동동작합니당!
- 기존에 id props 주입 부분이 삭제되었습니다.
```tsx
<CheckList
isChecked={false}
onToggle={checked => {
console.log(checked);
}}
onClick={() => {}}
>
```

CheckList 컴포넌트의 input id에 react18의useId 사용하기

---

src/components/common/ImageContent.tsx
src/components/common/TextField/MemoText.tsx
src/pages/add/image.tsx

일단 정말 순수하게 이미지 레이아웃만 작성했어요!
API에 수정도 필요한 상황이라.. 어떠한 기능도 들어가 있지 않지만, 전반적인 UI 작성 후에 `영감 추가`기능 작성 들어갈 예정입니다.
그리고 [태그 추가] 부분은 대윤님 작성이 끝난 뒤에 넣으려구요. 아직 추가 안 된 것 맞지요?!
- memoText의 fixedHeight이 405로 되어 있는데, 프레이머에서 아무리 봐도 405로 되어 있는 UI를 찾을 수가 없어서 일단 100으로 디자인 수정했습니다 (제가 잘못한 거라면 말씀해주세용)
- editable이라는 프롭스가 false라면 작성이 되지 않았는데, 영감 추가 페이지에서는 default가 작성이 되어야 하는 상황이라 writable이라는 프롭스를 추가했어요.(글 작성 o, 펜슬 아이콘 x) 후에 영감 수정하는 기능 넣을 때 전반적으로 리팩터링을 해볼게요!
... 나중에 이미지를 올리는 기능을 추가할 때, 핸드폰 갤러리랑 연동을 어떻게 해야할 지에 대해서는 고민 좀 해봐야할 것 같아요!
요건 한번 틈틈이 알아보겠습니다. 혹시 아시는 분 있다면 의견 환영입니다 :)

영감 추가 - 이미지 타입

---

src/components/common/TextField/Input.tsx

- Input 컴포넌트가 textarea일 때 `resize` 속성이 없어 textarea 크기가 변경 될 수 있는 문제를 해결합니다.
Closed #109

Input이 textarea일 때 하단 resize 숨기기

---

src/components/LinkThumbnail.tsx
src/components/add/LinkInput.tsx
src/pages/add/link.tsx
src/utils/validator.ts

디자인 간단하게 작성했고..! 영감 추가 관련 기능은 아무래도 유저 기능이 개발된 이후에 api 본격적으로 붙이고, 할 수 있지 않을까 싶어요.
일단 여기까지 리팩터링 간단하게 거친 다음에 영감 보기 view로 이동할까 합니다!
유효성 체크하는 validator 유틸 함수를 작성했습니다.
input에 validator 프롭스를 넣으려고 하다가.. 제 페이지에서는 인풋에 잘못된 url을 넣으면 input 아래에 에러가 뜨는 것이 아니라,
toast 알람이 뜨기 때문에 해당 유틸 함수를 작성하는 것으로 했어요! 
나중에 확장하게 되면 훅을 작성해볼 수 있을 것 같은데, 아직까지 그 수준은 아닌 것 같아서 그냥 간단하게 validator.ts 정도로 멈췄습니다!

영감 추가 - 링크 타입 

---

src/pages/login/index.tsx

- navigationBar가 필요 없는 페이지에서는 mockUp 요소를 하나 만들어서 사용하도록 변경했어요.
- #99 이슈와 관련되어 있습니다
Closed #117

chevronLeft가 필요 없는 경우 navigationBar 대신 목업 요소 사용

---

src/components/common/Button/CTABottomButton.tsx
src/hooks/common/useUserAgent.ts
src/pages/test/index.tsx

오늘 디자이너분들께 전달받은 내용이죠!
ios인 경우 상하단의 padding이 바뀌는 것과, CTAButton 배경에 무조건 Gray 백그라운드가 들어가는 요소를 조합해서 만들었습니다.
> 저의 경우 좌우 패딩을 페이지에서 16px씩 주고, 버튼에는 상하 패딩 8px 주는 방식으로 작성했는데요, 다들 어떻게 하셨는지 궁금하네요. 만약 페이지에서 좌우 패딩을 안넣은 경우에는 버튼 wrapper에 좌우 패딩을 넣긴 해야되거든요. 혹시 다른 분들 어떻게 하셨는지 궁금합니다. 
만약 좌우 패딩을 페이지에서 안 넣는 경우가 있으신가요? 그렇다면 추가적으로 props를 넣으려고 합니다. 의견 주시면 필요 시에 추가할게요~

공용 컴포넌트 - CTABottomButton

---

src/components/TagForm/index.tsx
src/components/common/NavigationBar/NavigationBar.tsx
src/components/home/AppendButton.tsx
src/components/home/HomeNavigationBar.tsx
src/components/home/TagFormRouteAsModal.tsx
src/hooks/common/useInternalRouter.ts
src/hooks/common/usePreventScroll/index.ts
src/hooks/common/usePreventScroll/usePreventScroll.ts
src/hooks/common/useRouterQuery/index.ts
src/hooks/common/useRouterQuery/useRouterQuery.ts
src/pages/_app.tsx
src/pages/add/tag.tsx
src/pages/edit/tag.tsx
src/pages/index.tsx
src/pages/tag/index.tsx
src/store/FilteredTags/filteredTagsStates.ts
src/store/FilteredTags/index.ts
src/store/FilteredTags/useFilteredTags.ts
src/styles/GlobalStyle/GlobalStyle.tsx

작업 기간이 기간이니,,, 나눠서 개발할 수도 있었지만 개발 진척도를 위해 뭉쳐서 개발했슴다
**홈화면에 대한 부분**
- `/tag` route를 홈 화면에서 사용되는 태그 관리 route로 사용했습니다 + Route as modal로써 사용했습니다
- `components/home/TagFormRouteAsModal` 에서 query param을 기준으로 모달을 보여주었습니다. (children으로 page 컴포넌트를 렌더링합니다)
**공통되는 부분**
- `TagForm`이 `TagFrom`으로 돼 있어서 오타 수정했슴다
- 자료형 보장을 함께 할 수 있는 `useQueryParam` 훅을 개발했습니다
- Route as modal등에서 body의 스크롤 방지를 위한 `usePreventScroll` 훅을 개발했슴니다
- useQueryParam
```ts
const foo = useQueryParam('foo'); // string | undefined
const num = useQueryParam('num', Number); // number | undefined
const barNum = useQueryParam('foo-num', Number) ?? -1; // number
```
- usePreventScroll
```ts
const foo = useQueryParam('foo');
usePreventScroll(Boolean(foo)); // 안에 조건을 넣어주면 됨니다
```
- 리팩토링? 수정? 가능하다고 생각되는 부분은 `NOTE:` 달아놨어용
- 현재 홈 화면 태그 추가에서도 전역 …

홈 화면 - 네비게이션 바 + 태그 추가 개발 w/ 공용 훅

---

@types/tag.d.ts
src/components/common/Content/TagContent.tsx
src/components/common/Content/styles.ts
src/components/common/TextField/MemoText.tsx
src/components/common/TextField/TextField.tsx
src/components/common/styles.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx
src/remotes/tag.d.ts

- 영감 추가 | 상세에서 사용되는 Tag 컨텐츠를 추가했습니다.
-  영감의 Tag 리스트를 보여주며 **+버튼 눌렀을때 추가 | 편집**할 수 있습니다.
- 즉, onEdit Props로 각각에 맞는 추가 | 편집을 진행할 수 있도록했습니다.
- onClickTag를 이용하여 tag를 클릭했을 경우의 action을 props로 전달할 수 있도록했습니다.
- 디자인을 확인해보니 wrapper에서 padding 위아래 16px를 해주는 부분이 공통으로 사용되어 공통으로 선언하여 사용하도록했습니다.
- `contentWrapperCss`
- 해당 부분은 `~/components/common/Content/styles` 선언하여 공통 사용하도록했습니다! 의견있으면 알려주세요!
- 다른 부분도 뺄까? 하였지만 논의 이후 변경하는게 좋겠다고 생각했습니다!
- labelCss가 다른 부분에서도 사용되어 TexField안에서 common으로 빼내었습니다.
```tsx
<TagContent onEdit={() => { /** +버튼 눌렀을때 수정  | 편집 */}} tags={tags} />
```
```tsx
<TagContent onEdit={() => { /** 수정  | 편집 */}} tags={tags}  onClickTag={() => {/** 단일 tag 클릭 action */}} />
```
```tsx
import { contentWrapperCss } from '~/components/common/Content/styles';
<section css={addImageTopCss}>
<div …
```

영감 추가 | 상세 - 태그 컨텐츠 추가

---

src/components/common/Button/CTABottomButton.tsx
src/components/common/Button/index.tsx
src/pages/signup/email-verified.tsx

- ~CTABottomButton에 `absoulte bottom` 속성을 줬어요~
- ~CTABottomButton에 `bottom` 인자를 추가했어요~
- `components/common/Button`에서 import 할 수 있도록 export문을 작성했어요
- `signup/email-verified` route에 CTABottomButton을 적용했어요
- 기존에 space-between 이용하실려고 작성해두셨던 스타일링은 걷어내봤어요
은정님께서 작성해주신 내용과 크게 다르지 않게 사용할 수 있슴다
```jsx
<CTABottomButton>기본 버튼</CTABottomButton>
<CTABottomButton bottom="12px">bottom 12px 버튼</CTABottomButton>
```
원래 도현님과 말씀나눴던대로 email-verified 페이지에 적용할 생각을 하다, 
아예 바닥에만 붙혀둘 용도인가? 생각이 들어서 적용해봤어요 !!
> 은정님께 말씀드리고 수정했었어야 했는데 죄송합니다 ..
`absoulte` 속성에 대해 제가 파악하지 못한 다른 의미가 있으시면 말씀해주세요 !!!
`CTABottomButton`에서 걷어내고 page내에서도 핸들링 가능하니 편하게 말씀해주시면 좋을 거 같아용 👍

singup/email-verified CTABottomButton 적용 및 CTABottomButton 업데이트

---

src/components/common/icons/RemoveCircleIcon.tsx
src/components/my/Menu.tsx
src/components/my/tag/MyTagItem.tsx
src/pages/my/tag/index.tsx
src/remotes/tag.d.ts

- 마이페이지에서 공통을로 사용되는 `Menu` 컴포넌트 추가했습니다.
- 살펴본 결과 Menu에서는 label과 오른쪽 IconButton이외의 사용을 못보아서 flex & space-between를 이용해서 개발했습니다.
- 마이패이지의 태그 관리 페이지 개발하였습니다.
- `Menu`를 이용해서 `MyTagItem`을 개발하여 사용했습니다.
- **디자이너분들과 협의 이후 좌우 padding 16px 된 divider 적용하는것으로 논의되었습니다**
- CTAButton 머지되면 추가 예정입니다.
- 혀바닥 Modal은 추후 개발해서 적용하겠습니다.
- 테그 등록 모달
- #138 
- label과 오른쪽 IconButton 넣어주시면됩니다!
```tsx
<Menu
label={tag.content}
rightElement={
<IconButton
onClick={() => {
onDelete(tag.id);
}}
iconName="RemoveCircleIcon"
light
/>
}
/>
```
```tsx
<MyTagItem
key={tag.id}
tag={tag}
onDelete={id => {
id;
}}
/>
```

마이페이지 - 태그 관리

---

src/components/common/Dialog.tsx
src/components/common/IllustDialog.tsx
src/pages/test/dialog.tsx

- IllustDialog를 만들었습니다.
- 원래는 Dialog에서 대응하려고 했으나, 레이아웃 변경이 커서 새로운 컴포넌트로 분리하는게 낫겠다는 판단을 내렸습니다.
- 이미지 소스는 240x160 이여야합니다.
- 추후 일러스트 같은 static 이미지를 어디에 저장할 것인지 의논해봐야 할 것 같아요
테스트 링크: https://1b761a72.ygt.pages.dev/test/dialog
Closed #144

공통 컴포넌트 - Dialog 이미지 대응

---

src/components/common/LoadingHandler/LoadingHandler.tsx
src/components/common/LoadingHandler/index.tsx
src/components/common/Spinner/FixedSpinner.tsx
src/components/common/Spinner/Spinner.tsx
src/components/common/Spinner/index.tsx
src/pages/tag/index.tsx

- 디자인 스펙대로 100px 100px 크기를 갖는 `Spinner` 컴포넌트를 개발했어요
- Fixed로써, 100vw, 100vh 크기를 갖으며 중앙에 Spinner가 위치한 `FixedSpinner` 컴포넌트를 개발했어요
- `AnimatePresense`와 함께 Suspense랑 비슷하게 쓸 수 있는 방법이 없을까? 생각하여 고안해낸 `LoadingHandler`를 개발했어요.
- 로딩 상태와 로딩 시 보여줄 컴포넌트와 함께 사용해요
- [AnimatePresence 공식 문서](https://www.framer.com/docs/animate-presence/##unmount-animations)에서 확인할 수 있듯이 key 값이 필요하여 useId를 사용했어요
- 자세한 사용 방법은 아래를 참고해주세요
https://user-images.githubusercontent.com/26461307/168117698-31e56476-b844-47d9-bb3b-f1b9828cf167.mov
FixedSpinner + LoadingHandler 적용 예시
- LoadingHandler
```jsx
import { FixedSpinner } from '~/components/common/Spinner';
function Foo() {
const { tags, isLoading } = useGetTagListWithInfinite({});
return (
<article>
<NavigationBar title="태그 추가" backLink="/" backLinkScrollOption={false} /> …
```

Spinner, FixedSpinner, LoadingHandler 컴포넌트 개발

---

src/components/common/BottomSheetModal.tsx
src/components/common/Dialog.tsx
src/components/common/IllustDialog.tsx
src/components/home/AppendButton.tsx
src/components/home/TagFormRouteAsModal.tsx
src/hooks/common/useWindowSize.ts
src/pages/_app.tsx
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx
src/pages/my/tag/index.tsx
src/pages/signup/email-verified.tsx

height가 계속 잘리는 걸 계속 눈에 밟혀서 간단하게 작업해보았습니다..
전 항상 이런식으로 적용해왔었는데, 다른 더 좋은 방법 경험해보신 것 있다면 말씀해주세요! :)
useWindowSize 훅을 쓰는 이유는 url바가 자동으로 사라지고 생성되는 환경을 위해서(특히 카카오 인 웹) 적용했습니다!
100vh 대신 `calc(var(--vh, 1vh) * 100)`으로 적어주시면 됩니다.

레이아웃 - 모바일 url 바에 따른 100vh 자동 조절

---

src/components/add/ImgUploader.tsx
src/components/common/ImageContent.tsx
src/components/common/TextField/MemoText.tsx
src/components/home/AppendTooltip.tsx
src/hooks/common/useImgUpload.ts
src/pages/_app.tsx
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx
src/pages/test/index.tsx

issue #187 해결했습니다.
- 이미지 콘텐츠를 업로드 한 후 x 버튼을 클릭했을 때 자동으로 이미지 업로드 인풋이 다시 활성화되는 기능을 추가했습니다. (디자이너 분들 답변)
- 해당 img uploader와 useImgUpload를 공통 컴포넌트와 공통 훅으로 재사용할 수 있도록 했습니다. (이미지 업로더는 add 폴더 안에 넣긴 했어요..! )
이미지 업로드 페이지에서 메모를 함께 fetching할 수 있도록 수정했습니다.
이제 대윤님이 태그만 이어붙여주시면 될 듯! 부탁드립니다..!

영감 추가 - 이미지 추가 기능 완성 및 업로드 에러 해결

---

src/components/TagForm/index.tsx
src/components/add/AddTagFormRouteAsModal.tsx
src/components/common/Content/TagContent.tsx
src/components/common/TextField/SearchBar.tsx
src/hooks/api/tag/useGetTagListWithInfinite.ts
src/hooks/api/tag/useTagMutation.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/tag.tsx
src/pages/add/text.tsx
src/pages/index.tsx

- 해성님의 TagFormRouteAsModal 기반으로 AddTagFormRouteAsModal을 만들었습니다.
- 아직 API가 업데이트 전이라 동작이 원활하게 될 수 있도록 구현했습니다.
- keyword를 submit을 했을 경우, 
- Tag가 있으면 그것을 save하였습니다.
- Tag가 없으면 create한 tag를 save하였습니다.
- keyword를 기반으로 search를 할 수 있도록 onSearch를 구현했습니다.
- 추가작업으로 lodash import부분 변경 및 단건 검색`/v1/tag/search/${keyword}`의 params를 변경하였습니다.
tag list 무한 스크롤 아직 진행안했습니다!
isLoading만을 업데이트를 바라보고 싶은데...흠....
```tsx
useEffect(() => {
if (!isLoading) onSearch && onSearch(keyword);
if (!isLoading && keyword) {
if (!tags.length) {
saveCreatedTag(keyword);
} else {
onSave(tags[0]);
}
setValue('');
}
// eslint-disable-next-line react-hooks/exhaustive-deps
}, [isLoading]);
```
아래처럼 useRef() 사용해서 이전 키워드를 저장해서 비교해서 검색하도록 변경했습니다.
```tsx
const lastKeyword = useRef<string | null>(null);
useEffect(() => {
if (keyword === …
```

영감 추가 - 태그 추가 API 적용

---

src/hooks/api/reissue/useReissueMutation.ts
src/hooks/common/useDidUpdate/useDidUpdate.ts
src/hooks/common/useRouterGuard.tsx
src/libs/api/client.ts
src/pages/_app.tsx
src/store/User/UserProvider.tsx

- 비로그인시 non public route에 접근하면, 로그인 화면으로 가도록 대윤님께서 작업해주신 `useRouterGuard`를 수정, 사용했슴니다
- useRouterGuard는 UserProvider에서 사용하였는데 전체적인 흐름은 아래에서 설명드릴게오
- `useDidUpdate`의 의존성 배열을 수정하였어요.
-  기존에는 array를 통채로 넣어줬으나, 의존성 배열에서 array는 레퍼런스로 비교한다하여 예상한대로 동작하지 않다고 판단하여 스프레드 연산자를 사용하는 방법으로 수정하였습니다
- reissue 전에 사용하던 `api client`의 로컬스토리지를 읽는 인터셉터를 지웠어요
- `useReissueMutation`에서 성공 시에 필요한 콜백을 주입받아 `onSuccess` 시에 실행하도록 수정했어요
https://user-images.githubusercontent.com/26461307/168230041-3162a7dc-f177-4927-9c6e-6daae0277329.mov
> 제 테스트용 계정이 비밀번호가 4자리라 .... form에서 걸려서... 슬랙에 올려진 은정님 게정 사용했읍니다 ...
1. `useUser`의 `isLoaded`는 다음의 경우에 true가 됩니다
- 쿠키에 refreshToken이 없는 경우
- refreshToken이 있으며, reissue에 성공한 경우
2. `useRouterGuard`의 `isRouterGuardPassed`는 다음의 경우에 true가 됩니다.
> isLoaded가 false일 시 연산하지 않습니다.
- useUser의 …

Router Guard 적용 및 Reissue mutation 수정

---

src/components/TagForm/index.tsx
src/components/common/Content/TagContent.tsx
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx
src/pages/index.tsx
src/pages/tag/index.tsx

- 테그 Link as를 정확하게 사용하기위한 업데이트를 진행했습니다.
- TagForm에 readOnly props를 추가하여 create하는 경우를 분기해서 사용할 수 있도록했습니다.
https://user-images.githubusercontent.com/59507527/168290132-62d6e17b-5873-487e-b899-60436ad2920a.mov
https://user-images.githubusercontent.com/59507527/168290231-c2287282-1923-4a01-a479-c85b809bf830.mov
```tsx
<TagForm
applyedTags={filteredTags}
registeredTags={tags}
onSave={addTag}
onRemove={removeTag}
onSearch={keyword => {
setKeyword(keyword);
}}
readOnly
/>
```

테그 - 추가 모달 버그 및 readOnly추가

---

src/components/home/Thumbnail.tsx
src/pages/index.tsx
src/remotes/inspiration.d.ts

영감 리스트 조회 서버 스펙 중 `TagResponse`가 `TagResponses`로 변경된 것을 대응하였읍니다

영감 인터페이스 중 TagResponses 대응

---

src/components/TagForm/AppliedTags.tsx
src/components/TagForm/index.tsx
src/components/common/Tag.tsx
src/hooks/api/tag/useTagMutation.ts

- `됫다고 쳐` 부분의 주석을 제거하고 create한 데이터를 onSave하도록 변경했습니다.
- CreateTagDataResponseInterface을 /v1/tag/add 리턴 타입에 맞게 변경했습니다.
- React.memo 작업과 첫 지정색으로 그리도록하는 작업을 진행했습니다.
https://user-images.githubusercontent.com/59507527/168322236-ee424f70-0259-47e3-b182-964c1fe903f0.mov
###TagForm 에서  onSave에  tag create return data를 집어너어 바로추가하는 형태로 했습니다.
```tsx
const saveCreatedTag = useCallback(
(keyword: string) => {
createTag(keyword, {
onSuccess: data => {
onSave(data);
},
});
},
[createTag, onSave]
);
```

영감 추가 - 테그 추가 API 적용 및 Tag React.memo 적용

---

src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
src/hooks/api/inspiration/useInspirationMutation.ts

영감 추가 후 메인 페이지로 돌아가면서 기존 cache를 리셋하고 다시 받아옵니다.

영감 추가 후 메인 리스트 리프레시

---

src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx
src/store/AppliedTags/useAppliedTags.ts

- useEffect의 return 문으로 메모리 해제될 경우, 해당 로직을 수행하게 합니다.
- isUseUnmounted를 파라미터로 받아 사용될 경우에만 실행 시키도록합니다.
https://user-images.githubusercontent.com/59507527/168345410-da2e43c3-4f0d-4831-938b-ea436f02ccae.mov
```tsx
const { tags } = useAppliedTags(true);
```
```tsx
const { tags } = useAppliedTags(); // or false
```

영감 추가 - unmounted일 때, tags 초기화

---

src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
src/hooks/api/auth/useSignupSendEmailMutation.ts
src/hooks/api/sign-up/useCheckExistsNicknameMutation.ts
src/hooks/api/sign-up/useCheckExistsSignupMutation.ts
src/hooks/api/sign-up/useSignupMutation.ts
src/hooks/common/useInternalRouter.ts
src/pages/login/index.tsx
src/pages/signup/email-verified.tsx
src/pages/signup/index.tsx
src/pages/signup/sent-email.tsx
src/remotes/auth.d.ts

- login
- 로그인 폼 초기 상태에서 체크 표시 수정
- signup
- 이메일 가입 여부 확인 후 메일 전송 뮤테이션 적용
- signup/sent-email
- 이메일 승인 여부 확인 후 모달 띄우기 구현
- signup/email-verified
- 가입 완료 로직
- 문제점1: signupSuccess effect 안에서 router.push가 안됩니다. 정확히는 주소는 변경되는데, 페이지 리프레시가 일어나지 않아요. memo 같은 것을 사용한 것도 아니라서 추후에 디버깅이 필요합니다 ㅠㅠ
- 해당 문제는 우선 window.location.replace()로 구현해놨어요

회원가입 - api mutation & 기능 연동

---

src/hooks/common/useInternalRouter.ts
src/pages/tag/index.tsx

- 홈 태그 필터 화면에 기획상 존재하였던 완료 버튼을 추가했어요
- RouteAsModal과 같이 사용될 때, 다양한 부분에서 `scroll: false`로 push를 할 수 있다는 생각에, 
`useInternalRouter`에 `scrollPreventedPush`를 추가해봤어요
```jsx
const router = useInternalRouter();
router.scrollPreventedPush('/');
// router.push('/', undefined, {scroll: false}); 와 동일
```

태그 필터 화면 완료 버튼 추가 및 useInternalRouter 추가 기능 개발

---

src/components/common/LoadingHandler/LoadingHandler.tsx
src/components/home/EmptyImageSection.tsx
src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
src/pages/index.tsx

- 홈 화면에서 "영감에 부착된 태그 선택" 후 "영감에 부착되지 않은 태그 선택했을 시" 이미지가 렌더링되지 않는 문제를 해결했어요
- `useGetInspirationListWithInfinite` hook에서 `isEmpty`를 내려보내도록 리팩토링 했어요
가장 공유하고 싶은 이슈는 `AnimatePresence` 관련 이슈임니다
현재 해결 방법으로 2가지가 있는데, (문제점은 이슈에 적어 두었어요 #224 )
1. 삼항 연산자를 이용해 컨디셔널 렌더링 
```diff
+ empty일 때 썸네일 wrapper section 태그가 렌더링되지 않음
- 이미지의 exit 애니메이션이 발생하지 않음 (이미지 컴포넌트에 key 값을 적용하지 않아서)
```
```jsx
{isEmpty ? (
<EmptyImageSection />
) : (
<motion.section
css={thumbnailWrapperCss}
layout
layoutId="thumbnailSection"
variants={staggerHalf}
initial="initial"
animate="animate"
exit="exit"
>
{...}
</motion.section>
)}
```
2. 이미지에만 컨디셔널 렌더링을 적용
```diff
+ 이미지의 exit 애니메이션이 발생함
- empty일 때 썸네일 wrapper section이 렌더링됨 (물론 썸네일은 렌더링되지 않고, section 태그만 렌더링됨)
```
```jsx
{isEmpty && <EmptyImageSection key="loading section" />} …
```

홈 화면 Empty 이미지 렌더링 문제 해결

---

src/components/add/AddTagFormRouteAsModal.tsx
src/components/common/NavigationBar/NavigationBar.tsx
src/components/home/TagFormRouteAsModal.tsx
src/components/inspiration/InspirationViewAsModal.tsx
src/pages/content/[contentId].tsx
src/pages/tag/index.tsx

- `/tag` route 이자 `TagFormRouteAsModal`에서 스크롤이 가능하도록 하였어요
(body는 스크롤 방지하며, Modal만 스크롤되게)
- 영감보기 화면에서 body가 스크롤되는 것을 방지했어요
`AddTagFormRouteAsModal`의 `usePreventScroll`을 사용하지 않도록 했어요
사이드 이펙트 확인했습니다
- NavigationBar를 `position: sticky`로 수정했어요
스크롤 시 상단에 위치하기 위해서입니다. 사이드 이펙트 확인했어요
- 영감보기 스크롤 가능 + body 스크롤 방지
https://user-images.githubusercontent.com/26461307/169227284-7b1d74db-58ac-4342-910c-e29de744a37e.mov
- 태그 필터 스크롤 가능 + body 스크롤 방지
https://user-images.githubusercontent.com/26461307/169227393-27cec444-3b16-4b4d-8db7-fc9730867306.mov
- 태그 추가 스크롤 가능 + body 스크롤 방지
https://user-images.githubusercontent.com/26461307/169227428-78379ff7-26b1-4e09-9ff9-354b39477e0c.mov
`NavigationBar`의 경우 많이 사용하시고 계셔서 사이드 이펙트를 전부 확인한 것은 아니지만,
없을 것이라 생각해요! 하지만 혹시나 이슈가 있으실 시 말씀해주시면 제가 수정해보겠습니다 ~!
---
`RouteAsModal` …

태그 필터, 영감 보기 스크롤 이슈 해결

---

src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
src/hooks/common/useAuthorizationIntercept.ts
src/libs/api/client.ts
src/pages/test/user.tsx
src/store/User/UserProvider.tsx
src/store/User/useUser.ts

- accessToken이 만료되었을 경우 axios interceptor를 통해서 갱신하는 로직을 만들었습니다.
- react-query를 사용하고 싶었는데, interceptor 안에서 모든 작업을 끝내야될 것 같더라고요. (hooks 기반의 비동기 처리가 어렵습니다.) 그래서 post api instance를 직접 로직에서 사용하였습니다.
- 또한 위와 관련된 작업으로 api instance의 interceptor를 교체할 수 있도록 하였습니다.
- api instance의 accessToken은 인터셉터가 아니라, config로 처리할 수 있도록 변경하였습니다.
- 추후에 #246 에서 만든 userLogout 적용 예정입니다.
- /test/user 에 유저 관련 테스트를 도와주는 페이지를 만들었습니다.
> 관련되서 비슷한 작업을 해보신 분이라던가, 더 깔끔하게 처리할 수 있는 방법을 아시는 분들은 자유롭게 제안주셨으면 합니다~!!
401 -> reissue -> 재요청 (200) 확인하였습니다!

인증 토큰 만료 시 갱신 후 재요청

---

src/hooks/ga/useGaPageview.ts
src/libs/ga/ga.test.ts
src/libs/ga/ga.ts
src/libs/ga/index.test.ts
src/libs/ga/index.ts
src/pages/_app.tsx
src/pages/_document.tsx

- `GA`를 적용했어요
- `GA`의 pageview, event 유틸을 개발했어요
- `_app`에서 next router.event를 사용해 ga pageview hook을 개발, 적용했어요
- `Hotjar`를 적용했어요
- `_document`에서 `<meta name="viewport" .../>`에서 발생하는 경고를 참고하여 `_app`에 적었어요
- https://nextjs.org/docs/messages/no-document-viewport-meta
```jsx
import { gaEvent } from '~/libs/ga';
gaEvent({ action: "무슨 액션" })
gaEvent({ action: "무슨 액션", category: '카테', label: '라벨', value: '밸류' })
```
- 원래 `Next/Script` 태그를 이용해 GA를 부착할려 했으나, gtag 관련 오류가 나더라구요. 그래서 이전에 적용하던 방식대로 `_document`에서 적용했어요 (https://nextjs.org/docs/messages/next-script-for-ga)
- GA ID, Hotjar ID 둘 다 결국에는 노출되어 상관없으나, 저는 환경 변수로 관리하곤 했었어요. 여러분들은 어떻게 관리하셨는 지 궁금해요!! 
> cloudflare page에 환경 변수 적용해두었어요

GA, Hotjar 적용 및 유틸 개발, 적용

---

src/components/common/TextField/Input.tsx

iOS에서 disabled input의 텍스트 색상이 흐려지는 현상 방지하기 위해 아래 레퍼런스를 참고해서 css 프로퍼티를 추가합니다.
- https://stackoverflow.com/questions/262158/disabled-input-text-color-on-ios

design: iOS disabled input text color 흐려짐 방지

---

src/components/add/AddTagFormRouteAsModal.tsx
src/components/home/TagFormRouteAsModal.tsx
src/components/home/Thumbnail.tsx
src/components/inspiration/InspirationViewAsModal.tsx
src/constants/common.ts
src/pages/content/index.tsx

[next export build로 인한 dynamic routing 제거](https://github.com/depromeet/11th_7team_web/commit/8d82f6babac58e9bfb9446fdcc96c3d30f7bbd1c)
`content/inspirationID` route에서 새로고침을 했을 때 발생했던 404 에러가 있었어요.
원인은 결국 next export and build 방식으로 정적 빌드하는 방식 때문에 다이내믹 루트를 사용할 수 없는데,
제가 계속 그 사실을 잊고서 개발을 해버린 데에 원인이 있네요 😂 export 하는 방식을 사용하는 순간 
getServerSideProps도 넌센스인데, 이걸로 해결할 생각을 하고 있었어요.. ㅎㅎ
그래서 지금은 다이내믹 라우팅 제거하는 방식으로 해결해놓았습니다!
일단 클라우드 플레어 임시 브랜치 배포 사이트에서는 새로고침했을 때 문제 없는 것 확인했어요!
추후 머지 된 이후에 다시 한번 확인해볼게요~

next export build로 인한 dynamic routing 제거

---

src/pages/content/index.tsx

`pages/content/index.tsx` 를 주석처리해가며 처리해본 결과, 다음과 같은 순서로 실행되더라구요!
1. 네비게이션 백 버튼 클릭 (router push)
2. push 전, pages/content/index.tsx 의 useEffect 트리거 (쿼리파람을 통해 가지고온 inspiration ID가 undefined > [inspirationById, null] 키 값의 영감을 조회 > 영감이 바뀌어서 트리거됨)
3. 기존 네비게이션 백 버튼 푸시는 무마되며 useEffect의 scroll false가 없는 push가 실행
해결 방법
- useEffect의 router push에 scroll 옵션을 넣어서 해결할 수 있었어용

영감 조회 시 스크롤 복구 로직 수정

---

src/components/LinkThumbnail.tsx
src/pages/content/index.tsx

inspiration 상세 뷰에 motion을 적용했습니다.
`defaultFadeInScaleVariants` 요게 기본적으로 페이지마다 들어가 있는 모션으로 보여서 추가했는데, 디자이너 분들 의견도 받아보면 좋겠네요 :)
```jsx
<a
css={linkThumbnailLinkCss}
href={thumbnail.url}
onClick={onOpenUrl}
target="_blank"
rel="noopener noreferrer"
>
```
target, rel 프로퍼티를 추가했고, 배포 후 이어서 어플에서도 체크해볼게요!
일단  `target="_blank"`만으로는 해결이 되지 않아서, 따로 리액트 네이티브 코드를 추가해주었어요! 그렇게 하면 앱에서도 링크 썸네일 클릭했을 때 사용자 모바일의 default browser로 새로운 창 이동이 됩니다.

영감 상세 보기 애니메이션 추가 및 링크 썸네일 새 창으로 열기 추가

---

src/components/common/TextField/Input.tsx
src/components/common/TextField/MemoText.tsx
src/components/inspiration/ImageView.tsx
src/components/inspiration/LinkView.tsx
src/components/inspiration/TextView.tsx

onBlur 이벤트를 추가했습니다. 펜슬 버튼을 눌러서 메모를 저장하듯이, 인풋이 블러될 때 자동 저장되면서 toast가 뜹니다.

영감 memo 수정 시 focus out 될 때 저장

---

src/hooks/api/auth/useSignupSendEmailMutation.ts
src/hooks/api/sign-up/useCheckExistsSignupMutation.ts
src/pages/signup/index.tsx
src/pages/signup/sent-email.tsx

- `/signup`에서 로그인으로 되어 있던 버튼을 `다음` 으로 수정했어요
- framer를 확인해보니 이메일이 아닐 때도 `disabled` 상태여서 관련 로직을 추가했어요
[보이스카웃 규칙](https://johngrib.github.io/wiki/Boy-Scout-Rule/)이 눈에 밟혀 .... 몇가지 리팩토링도 해봤어요
- `useSignupSendEmailMutation`, `useCheckExistsSignupMutation`에서 effect로 관리되던 성공, 실패 로직을 useMutation의 onSuccess, onError에 위임했어요
- 다른 훅에서 사용되는 request params 인터페이스 명과 같이 `~Request`인 것을 `~Params`로 통일시켰어요
- 몇가지 주석을 끼얹었어요
저는 페이지 혹은 컴포넌트에서 로직을 `내부의 hook`으로 분리해서 추상화하는 방법을 좋아하긴 하는데,
여러분의 의견을 아직 듣지 못해서 적용해보진 않았어요 !!
예를 들자면,
```jsx
function Foo() {
const { value, isLoading } = useFetchValue();
useEffect(() => {
로딩에따라어쩌구저쩌구;
}, [isLoading])  
return <div> { value } </div>
}
```
이런 컴포넌트가 있다면
```jsx
export default function Foo() {
const { value } = useValueAtLocal();
return <div> { value } </div>
}
export default …
```

회원가입 시 버튼 텍스트 수정 및 회원가입 로직 리팩터링

---

src/components/home/Thumbnail.tsx

홈 화면의 썸네일의 크기가 가변적으로 들어가는 문제를 해결했어요
aspect-ratio 속성이 사파리 15버전부터 지원되어, 지원되지 않는 환경에서 발생한 것이였어요
https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#browser_compatibility
아래 css trick과 `@supports`문을 이용해 해결했어요
https://css-tricks.com/aspect-ratio-boxes/
위 트릭
- [aspect-ratio 브라우저 지원 mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#browser_compatibility)
- [aspect-ratio css 트릭](https://css-tricks.com/aspect-ratio-boxes/)

썸네일 크기 가변 문제 대응

---

cypress/integration/1_before_login/onboard.ts
src/components/home/Thumbnail.tsx
src/styles/GlobalStyle/GlobalStyle.tsx

위 사진처럼 iOS 환경에서 aspect ratio와 padding bottom이 동작하지 않는 이슈를 발견했어요
이를 해결하기 위해 하위 요소에 padding을 주었슴니다
>추가적으로 가끔가다 cypress 테스트 통과하지 않는 것을 해결하기 위해 should option을 추가헀어용
https://stackoverflow.com/questions/58833459/cypresserror-timed-out-retrying-cy-click-failed-because-this-element-is-deta
> iOS 환경에서 버튼을 누르고 있을 때 예상치 않게 나오는 효과를 제거했어요
https://www.notion.so/depromeet/852cda9741824a92b4c8aec241dc14c1

썸네일 aspect ratio padding 대응

---

src/components/common/Tag/Tag.tsx
src/pages/my/tag/index.tsx

- iOS 환경에서 tag delete 버튼의 색상이 파란색으로 나오는 것을 대응했어요
- `/my/tag` route에서 완료 버튼에 뒤로 갈 수 있도록 동작을 추가했어요

iOS tag delete 아이콘 색상 대응, /my/tag route 완료 버튼 동작 추가

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/hooks/api/member/useMemberSignOutMutaion.ts
src/pages/my/account/index.tsx
src/pages/my/index.tsx
src/pages/signup/email-verified.tsx

- 정보 초기화 API 적용했습니다.
- 상세는 삭제 처리되었으나 리스트에서는 계속 보여지는 오류가 발생 중입니다.
- 계정 삭제 API 적용했습니다.
- 계정 가입 - 회원정보 입력에서 오류 문구가 TOAST에 그래로 나오도록 변경했습니다.
ex) '모든 입력 값을 적어주세요.' -> '닉네임은 4자 이상 20자 이하여야 합니다.'
```ts
if (nicknameError !== '' || passwordError !== '' || passwordRepeatError !== '') {
return fireToast({ content: '모든 입력 값을 적어주세요.' }); // as-is
return fireToast({ content: nicknameError || passwordError || passwordRepeatError }); // to-be
}
```
https://user-images.githubusercontent.com/59507527/170886027-d98d897f-e9c9-47b2-aa34-ddb42e3f7e7f.mov

설정 - 정보 초기화 API | 계정 삭제 API 적용

---

src/hooks/common/useUser/useUser.ts

로그아웃 후 다른 계정으로 로그인할 시 캐시된 것이 남아 있는 문제를 해결했어요
- 로그인, 로그아웃 시 모든 react query 캐시를 clear 하는 방향으로 작업했어요
https://react-query.tanstack.com/reference/QueryClient#queryclientclear

로그인, 로그아웃 시 react query 캐시 clear

---

src/components/common/CheckList.tsx

- `CheckList` 컴포넌트의 설계 이슈로 무한 루프에 빠질 수 있는 이슈로 뒤로가기가 무한루프 때문에 동작안되어서 해당 로직을 제거했습니다.
- 일전의 혜성님이 올려주신 label htmlFor를 활용해서 더 간결하게 처리했습니다.
```tsx
<label htmlFor={`check-list-${id}`}></lable>
```
https://user-images.githubusercontent.com/59507527/171947209-5c80f0ee-32da-4f15-b719-81c9e6ae1314.mov

회원가입 - 뒤로 가기 버튼 동작하지 않음

---

src/components/my/tag/MyTagItem.tsx

- 태그 삭제 모달을  `MyTagItem` 컴포넌트에 넣었습니다.
- 이벤트를 전달하는 방식으로 부모 컴포넌트에서 Dialog하나 가지고 처리하려다가 어차피 show아니면 <></> 상태여서  `MyTagItem`에 넣는 방식을 사용했습니다.

태그관리 - 태그 삭제 모달 구현

---

src/components/add/LinkInput.tsx
src/components/home/ThumbnailContent.tsx
src/components/inspiration/LinkView.tsx
src/hooks/api/inspiration/useIgnoreOpenGraph.ts
src/hooks/api/inspiration/useIgonreOpenGrap.ts

- `useIgonreOpenGrap` hooks를 생성했습니다.
- `useIgonreOpenGrap` og 수집이 막힌 url을 검증 및 막힌 url 기반한 내부적으로 사용하는 og를 만들어내는 기능을 담고 있습니다.
- 논의 된 사항으로 og 수집이 막힌 url의 대표 URL(origin)을 title로 하는 og를 만들어내어 적용하는 방식으로 진행했습니다.
```ts
const url = 'https://www.instagram.com/p/CeS3123v_byLlT1/?igshid=YmM312312yMTA2M2Y='
const { checkIgonreOpenGraphHost, makeURLOpenGraph } = useIgonreOpenGrap();
checkIgonreOpenGraphHost(url); // true | false
makeURLOpenGraph(url); 
/**
{
title: 'https://www.instagram.com',
url: 'https://www.instagram.com/p/CeS3123v_byLlT1/?igshid=YmM312312yMTA2M2Y=',
....
}
*/
```

영감 추가 - 링크 타입 (패이스북 | 인스타그램 대응)

---

src/components/common/TagForm/RegisteredTagList.tsx
src/components/common/TagForm/TagForm.tsx
src/components/common/TextField/SearchBar.tsx
src/pages/add/tag.tsx
src/pages/edit/tag.tsx

- 영감 추가 및 편집 - 영감 태깅에서 검색 로직 제거했습니다.
- onSearch, keyword 등을 삭제 하였습니다.
- 태그 폼의 padding 값을 재설정 해주었습니다.
논의에 따른 적용 내용
```
-기존안 최대한 유지-
태그 필터에서는 검색만, 태그 추가에서는 추가만 (기존 리스트는 제공, 검색불가능)
```

영감 추가|편집 - 영감 태깅 플로우 변경 대응 & 태그 폼의 padding 값을 재설정

---

src/pages/my/account/change-nickname.tsx
src/pages/signup/email-verified.tsx
src/store/UserInformation/useUserInformation.ts

- 닉네임 변경 시 검증, mutation에 trim된 값을 사용하도록 수정했어요
- 회원가입도 동일하게 trim된 값을 사용하도록 수정했어요
- 프로덕션 환경에서 `/my/account` -> `/my/account/change-nickname`으로 이동할 시 `userInformation`이 empty된 문제 해결중
- 직접 `/my/account/change-nickname`으로 접속할 시 이상없음
-> `useChangeNickname/useDidUpdate`의 의존성이 `userInformation.nickname`이 걸려있는데
이전에 방문한, 즉 이미 캐싱된 값은 userInformation에서 달라지지 않아 발생한 문제
-> useInput의 initialValue를 사용하여 해결
- 프로덕션 환경에서 `/my/account/change-nickname`의 초기 에러메시지(동일할 때)가 등장하지 않음
- `useDidUpdate`의 의존성이 nickname.debouncedValue가 걸려있어 트리거되지 않는 것이였음
-> 처음 방문할 시에는 항상 같은 닉네임이니 초기값으로 설정하여 해결

닉네임 변경 로직 보수

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/pages/edit/tag.tsx

- 네트워크가 느린 환경에서 영감 태깅 API를 중복해서 사용할 경우, 똑같은 ID의 tag들이 중복 태깅되는 이슈를 해결했습니다.
- `addInspirationTagIsLoading`을 통해서 mutate의 로딩을 확인하고 `true`일 경우, toast 메시지 중복 API 호출을 방지했습니다.

fix: isLoadign으로 tag 추가 연속 클릭시, 중복 적용 방지

---

src/components/home/AppendButton.tsx
src/components/home/AppendTooltip.tsx

Closed #366 
홈 화면에 있는 플러스 버튼 플로팅이 safe-area가 적용되지 않으면서 생기는 이슈 같아서 수정했어요!
@positiveko 요거 확인 좀 부탁드려도 될까요!!?

플러스 버튼 플로팅 위치 수정

---

src/components/common/TagForm/TagForm.tsx
src/hooks/api/inspiration/useInspirationMutation.ts
src/hooks/api/tag/useTagMutation.ts
src/hooks/api/tag/useTagRefresh.ts

#367 번과 #376 번을 해결했어요
- #367 번의 경우 영감을 추가할 때 영감 리스트를 invalidate하는 방식으로 해결했어요 538b3ff8e7f8a3c5fbf29e4cf8fdfb9984bd8ece
기존에 작성돼있는 영감 추가 mutation에 refresh 로직이 부착되어 있는데, 사용하는 곳에서 `onSuccess`를 오버라이드해서 발생한 문제였어요.
- #376 번은 영감에 태그를 추가, 삭제할 때 영감 리스트를 invalidate하여 해결했어요. 636c92e252fd9fa754638dd9abedaadf74c4eb5f
- 영감 괸리 화면에서 영감을 추가, 삭제 했을 경우 홈 화면과 개별 영감 화면에서 적용되지 않는 이슈
- 홈 화면 영감 리스트 조회를 reset 했어요
- 영감 개별 조회 캐시를 모두 삭제해요 (어떤 영감이 해당 태그에 부착돼있는 지 모르기 때문에)

태그 추가 시 태그 리스트 반영, 영감에 태그 부착 시 영감 리스트 반영

---

src/components/home/ThumbnailContent.tsx

- useEffect에서 동일 요소 참조가 이루어지고 있어서 문제가 생기는 것 같아서 수정했습니다! 우선 리렌더는 안일어나요

링크 섬네일에서 og 데이터가 없는 경우 멈춰버리는 현상

---

src/components/LinkThumbnail.tsx
src/components/add/LinkInput.tsx
src/components/add/LinkThumbnail.tsx
src/components/home/ThumbnailContent.tsx
src/hooks/common/useOpenGraphImage/index.test.ts
src/hooks/common/useOpenGraphImage/index.ts
src/hooks/common/useOpenGraphImage/useOpenGraphImage.test.ts
src/hooks/common/useOpenGraphImage/useOpenGraphImage.ts
src/pages/add/link.tsx
src/pages/test/index.tsx

OpenGraph에서 image가 상대주소로 적혀있을 수도 있어, `LinkThumbnail`에서 `image`로 접근하는 것을 대체했어요.
- 기존 `ThumbnailContent` 컴포넌트에서 적용중이였던 로직을 `useOpenGraphImage`라는 hook으로 모듈화했어요
- 해당 훅의 테스트 코드를 작성했어요
- `components/LinkThumbnail`의 디렉토리를 사용하는 곳이 `add` 한 곳이라, `components/add/LinkThumbnail`로 옮겼어요 
closed #381

링크 영감 개별 조회에서 이미지 에러 대응

---

src/hooks/api/inspiration/useCheckLinkAvailable.ts

`http://` 혹은 `https://`로 시작하는 링크가 아닌 경우 부적합한 링크로 판단하는 것을
1. `http`로 시작하는 지 확인
2. 시작한다면 링크 그대로 사용
3. 시작하지 않는다면 `http://` 부착 하였어요
> http:// 로 요청을 하여도 대부분 https 로 리다이렉트 로직이 있기 때문에 https로 저장되어서 더 많은 범용성을 갖는 처리이지 않을까... 
생각했는데 확실하진 않아요!! 더 좋은 방법 생각해두신 게 있으면 공유부탁드려용
https://user-images.githubusercontent.com/26461307/172151730-55887f95-0634-4ffb-a466-c27ca7c96401.mov

link http 프로토콜 부착 로직 추가

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx

Closed #391
- #391 에서 설명되어 있는 문제를 해결합니다.
mutation 상단에서 onError 함수를 받을 수 있도록 구현하였는데, 다른 의견 있으시다면 달아주셔도 좋을 것 같아요!
@hyesungoh 님께서 제안해주신 toast까지 추가해서 머지하겠습니다

영감 추가에서 오류 발생 시 버튼이 다시 active되지 않는 문제

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx

함께 머지했어야되는데 실수로 머지를 먼저 해버려서... 그냥 피알 하나 더 만들었습니다.
- 영감 추가 (3개 모두)에서 오류가 발생하는 경우 toast 메세지를 띄우도록 했습니다.

영감 추가 오류 시 토스트 메시지 띄움

---

src/components/common/Spinner/FixedSpinner.tsx
src/pages/signup/index.tsx

- 회원가입 시 `이메일 가입 여부 확인`, `이메일 인증 여부 확인`, `이메일 발송`의 로딩을 핸들링하는 상태를 추가했어요
- 위 로딩 상태에 따라 disabled 적용 및 loading spinner를 추가헀어요
- 마운트 시에도 이메일 validate를 확인하도록 하여 초기에 disabled 상태이도록 했어요
- `FixedSpinner`에 opacity 옵션을 추가헀어요

회원가입 이메일 발송 로직 로딩 핸들링

---

src/components/my/Profile.tsx

Closed #398 
- 누락된 로그아웃 다이얼로그를 추가했어요.

로그아웃 다이얼로그 추가

---

src/components/add/LinkInput.tsx
src/hooks/api/inspiration/useCheckLinkAvailable.ts

- 링크 확인 시 다음과 같은 순서로 바꾸었어요
1. 사용자가 입력한 값 조회
2. 실패할 시 (url값이 없을 시) + https로 시작하지 않을 시, https 부착하여 조회
3. 실패할 시 + http로 시작하지 않을 시, http 부착하여 조회
- 기존 유효하지 않은 주소 토스트 메세지 로직을, 모든 방법으로 조회하였으나 실패한 경우에 발생하도록 했어요
- 링크를 확인하는 도중 로딩 스피너를 보여주었어요
closed #402

링크 확인 로직 변경 + 로딩 핸들링

---

src/hooks/api/sign-up/useSignupMutation.ts
src/pages/signup/email-verified.tsx

- 회원가입 후 새롭게 반환되는 토큰 값을 이용해 클라이언트 로그인을 하였어요.
- 로그인 후 root로 router push 했어요
- 기존 effect를 이용해 핸들링되던 회원가입 성공, 실패 로직을 onSuccess, onError에 위임했어요
closed #410

회원가입 후 로그인되도록 개발 및 성공, 실패 로직 위임

---

src/components/common/ImageContent.tsx

fix: image content min-height 100px로 수정

---

src/components/common/Spinner/FixedSpinner.tsx
src/pages/content/index.tsx

- `FixedSpinner` 컴포넌트가 간혈적으로 가로 가운데 정렬이 되지 않는 것을 해결했어요
- 영감 조회 시 로딩 처리가 되지 않는 것을 해결했어요
- 영감이 없을 시 early return하는 것이 문제였어요
closed #403 
closed #415

영감 조회시 로딩 핸들링 수정

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx

- 영감 생성 (로딩) 시를 기존 `disabled` state로 관리하던 것을 `useQuery`의 `isLoading`으로 위임했어요
- 로딩 중 FixedSpinner를 렌더링했어요
- 느린 인터넷 상황에서 중복 업로드 방지되는 것 확인했슴다

영감 생성시 로딩 처리

---

src/components/common/TextField/Input.tsx

disabled 된 input에서 (영감을 보는 페이지) placeholder가 진하게 표시되는 이슈를 해결했습니다.
```js
&:disabled {
/* iOS에서 disabled input 텍스트 색상 자동 흐려짐 방지 */
/* https://stackoverflow.com/questions/262158/disabled-input-text-color-on-ios */
-webkit-text-fill-color: ${inputValue !== '' ? theme.color.gray05 : theme.color.gray03};
}
```
`  -webkit-text-fill-color` 요거를 선택적으로 적용했어요!

input placeholder 일반 폰트색과 동일하게 보이는 이슈 해결

---

jest.setup.js
package.json
src/components/common/DropdownMenu/DropdownMenu.test.tsx
src/components/common/DropdownMenu/DropdownMenu.tsx
src/components/common/DropdownMenu/index.test.tsx
src/components/common/DropdownMenu/index.tsx
src/constants/common.ts
src/hooks/common/useInternalRouter.ts
src/pages/signup/information.tsx
yarn.lock

- `/signup/information` route를 public route에 등록했어요
- test 환경에서 css style을 확인할 수 있도록 `@emotion/jest` 설치 및 설정을 했어요
- DropdownMenu 컴포넌트를 개발했어요
- 현재 선택한 값을 사용하는 곳에서 알 수 있도록 하는 방법에 대해 많이 고민해봤어요
- 크게 생각한 방법은 `state, setState`를 props로 받는 방법과 현재 적용한 `forwardRef` 방법이에요.
- 사용하는 곳에서 setStating을 하는 것이 불편할 것 같은 판단 + select 태그에 대한 ref 사용이 사용하는 입장에서 더욱 직관적일 것 같아서 이렇게 적용해봤어요
- 다른 방법이나 피드백 완전 환영입니다 ~!
https://user-images.githubusercontent.com/26461307/174295461-d010316e-56c5-43de-bd7f-aa17bb977123.mov
```jsx
const MOCK_LABEL = 'label';
const MOCK_VALUES = ['foo', 'bar', 'baz'];
// 라벨과 함께
<DropdownMenu label={MOCK_LABEL} values={MOCK_VALUES} />
// 기본값과 함께
<DropdownMenu values={MOCK_VALUES} defaultValue={MOCK_VALUES[0]} />
```
```jsx
import { useRef } from 'react';
import DropdownMenu from …
```

DropdownMenu 컴포넌트 개발

---

src/components/common/DropdownMenu/DropdownMenu.test.tsx
src/components/common/DropdownMenu/DropdownMenu.tsx
src/hooks/api/sign-up/usePatchExtraInformation.ts
src/hooks/api/sign-up/useSignupMutation.ts
src/hooks/common/useInternalRouter.ts
src/libs/api/client.ts
src/pages/signup/email-verified.tsx
src/pages/signup/index.tsx
src/pages/signup/information.tsx
src/store/Signup/signupUserState.ts
src/store/Signup/useSignupUser.ts

- DropdownMenu를 forwardRef를 받는 형식이 아닌, state와 setState를 props로 받는 형식으로 변경했어요
- ref를 통해 value의 변경을 확인할 수 없을 뿐더러, 어차피 사용하는 곳에서 useRef 혹은 useState를 선언하는데 이렇게 ref를 받을 이유가 없어보였어요 ....
- signup mutation에서 route 이동을 `/signup/information`으로 하도록 변경했어요
- 해당 route의 수정된 문구도 적용했어요
- 추가 정보를 mutate하는 hook `usePatchExtraInformation`을 개발했어요
- 회원가입이 성공하였을 때 위 patch mutate가 진행되어야하기 때문에, `useSignupMutation`의 onSuccess 로직을 page단에 위임했어요
- 페이지단에서 onSuccess를 사용하게 되니, 가독성이 조금 떨어지는 거 같긴해요. 
요 부분에서는 mutate를 걷어내고 그냥 axios 요청으로 전환하는 방향도 고려해볼만한거같아요
- `/signup/information` route를 개발했어요
- ~추가적인 정보까지 입력 후에 회원가입을 하는 로직이 구현되어 있지 않아요~
- ~순서가 `닉네임, 비밀번호` > `추가 정보`인데 추가 정보까지 입력해야 회원가입 post를 보내는 적절한 방법이 무엇일까요?~
> ~localStorage로 관리하여 보내기에는 비밀번호가 포함되어 있어 ...~
- ~그래서 현재는 회원가입 후 route 이동만 추가 정보로 하는 형식으로 구현되어 있어요~
> ~그렇기 때문에 회원가입까지 …

회원가입 시 추가 정보 플로우 개발 

---

src/components/add/LinkInput.tsx
src/hooks/common/useDataShareMessage.ts
src/pages/add/link.tsx
src/pages/add/text.tsx

Native WebView 컴포넌트에서 onLoad, onLoadEnd, onProgress progress===1 모두 도전했지만 타이밍 맞추는 것에 실패했습니다.
그도 그럴것이 Native WebView가 web app의 mounted 시점까지 알기는 힘들것입니다.
따라서 handshake 방법을 차용하였습니다. 단계는 아래와 같습니다.
```
1.Native가 WebView를 엽니다.
2.WebView useDidMount가 되었을 경우,
- { type: SHARE_WEB_MESSAGE_STATE, data: 'READY' }을 Native로 보냅니다.
- ios | android에 맞는 target에 evnet를 달아줍니다.
3.Native는 { type: SHARE_WEB_MESSAGE_STATE, data: 'READY' }를 받아 공유할 데이터를 쏘아줍니다.
4.WebView는 setStateHandler로 데이터를 넘겨줍니다.
```
https://user-images.githubusercontent.com/59507527/173603021-1ba5eb1a-a353-4b24-ba84-5de5cc61c5d2.mov
선언부에 해당하는 state setter를 넘기면됩니다.
```ts 
export default function AddText() {
const inspiringText = useInput({ useDebounce: true });
useDataShareMessage(inspiringText.setValue);
}
``` …

영감 공유하기 - LINK | TEXT (머지 천천히 될예정입니다....)

---

src/hooks/common/useUser/useUser.ts

IOS일 경우, 번들 ID가 달라 webView가 localstoage를 공유하지 못했습니다.
따라서 로그인/로그아웃 할경우,
`refreshToken`를 native로 보내어 공유 storage에서 사용할 수 있도록 postMessage를 구현했습니다.
https://user-images.githubusercontent.com/59507527/174853339-5b247494-ec3a-44e5-81e6-7d9923c4a7c8.mov
관련 APP PR : https://github.com/depromeet/ygtang-app/pull/90

영감공유하기 - IOS 영감 공유를 위한 refresh token 전송 

---

src/components/common/NavigationBar/NavigationBar.tsx
src/pages/my/tag/AddTagBottomSheet.tsx

- 태그관리 등록 모달에서 완료 누를 경우 저장 Action 수행되도롥 변경
- `NavigationBar`의 onClickBackButton를 callBack 받도록 리팩토링했습니다.
- 해당 모달에서는 모달이 닫히는 기능을 수행해야됨으로 callBack받도록 변경했습니다.
https://user-images.githubusercontent.com/59507527/174868273-c2d1b148-83af-4e98-be0c-1566db4fb91f.mov
```ts
interface NavigationBarProps {
backLink?: RouterPathType;
backLinkScrollOption?: boolean;
title?: string;
rightElement?: ReactElement;
onClickBackButton?: VoidFunction;
}
export default function NavigationBar( ...
const handelOnClickBackButton = () => {
if (onClickBackButton) {
onClickBackButton();
} else if (backLink) {
router.push(backLink, undefined, { scroll: backLinkScrollOption });
} else {
router.back();
}
};
return (
<nav css={navCss}>
<IconButton iconName="ChevronIcon" light onClick={handelOnClickBackButton} />
....
... …
```

태그 관리 - 태그 등록 모달 완료 누르면 저장되도록 변경 

---

src/constants/common.ts
src/constants/sessionStorage.ts
src/hooks/common/useDataShareMessage.ts
src/hooks/common/useLoginRedirect.ts
src/hooks/common/useRouterGuard.tsx
src/pages/login/index.tsx

- 공유하기에서 접근할 경우, onBoard 페이지로 가지게되어 기존에 공유하려던 것을 한번 더해야되는 이슈 발생
- redirect를 queryString으로 남길 경우, onBoard -> login으로 갈때, 챙겨 주고 삭제 등등... 추가로직 발생함에 따라
- sessionStorage를 사용하는 hooks를 만들어 구현을 진행했습니다.
- 해당 페이지로 이동한 뒤에 session의 redirect를 clear해줍니다.
- 사용부에서 add 관련 path만 집어 넣을 수 있도록 구현했습니다.
https://user-images.githubusercontent.com/59507527/175775835-2fc75a4e-e419-490c-b664-831b9e969983.mov
```ts
const { getRedirect, setRedirect, goRedirect } = useLoginRedirect();
/**
goRedirect의 경우, 해당 페이지로 이동한 뒤에 session의 redirect를 clear해줍니다.
*/
```

공유하기 - 비로그인 접근할 경우, 로그인 이후, redirect 해주기

---

src/components/common/TagForm/TagForm.tsx
src/pages/add/tag.tsx
src/pages/edit/tag.tsx

- 기존의 TagForm에 비즈니스로직을 혼합하여 가지고 있던 부분을 제거하고 부모 컴포넌트로 이관했습니다.
- 이과정을 진행하면서, 부모(TagForm의 사용부)컴포넌트에서 `추가` 버튼을 통해 테그를 추가할 수 있도록 했습니다.
- 논의 되어야될 사항 
- 이슈는 `완료` 텍스트를 사용하지만
- 기존 `완료`를 했을 때 뒤로가지거나 하는 로직 추가가 애매한 점으로 남아있어
- 먼저 `추가`로 바꾸고 입력된 tag를 추가하는 로직만을 하도록 구현했습니다.
기존 필터 검색 부분 처럼 keyword가 입력될 때마다 keyword를 저장하고, onSubmit을 통해서 action을 실행할 수 있도록 개발했습니다.
```jsx
<TagForm
applyedTags={inspiration?.tagResponses || []}
registeredTags={tags}
onSave={saveTag}
onRemove={removeTag}
onSearch={keyword => {
setKeyword(keyword);
}}
onSubmit={onSubmit}
/>
```

태그 추가 - 상단 바 완료버튼 추가

---

.github/workflows/CI.yml
src/pages/signup/email-verified.tsx
src/pages/signup/information.tsx

App에서 SafeArea bottom이 없어져, CTA 버튼이 너무 하단에 위치하거나
크기 100%가 전체 높이를 나타내지 않아 `flex-grow`가 적용되지 않았던 문제를 해결했어요
- `signup/eamil-verified` route의 최상단 wrapper에 `padding-bottom: 32px`을 추가, `height: ${fullViewHeight()}`를 적용했어요
- `singup/information` route의 최상단 wrapper에 `padding-bottom: 32px`을 추가했어요
> `CTABottomButton`이 ios 환경일 경우 하단 패딩 8px을 갖기 때문에, 32px을 넣었어요 (디자인상 높이가 40px임니다)
<p>
</p>
closes #475

회원가입 CTA 버튼 위치 수정

---

package.json
src/components/common/BottomSheetModal.tsx
src/components/common/Button/IconButton.tsx
src/components/common/Dialog.tsx
src/components/common/IllustDialog.tsx
src/components/common/ImageContent.tsx
src/components/common/icons/DownloadIcon.tsx
src/components/common/icons/index.ts
src/components/common/styles.ts
src/components/home/AppendButton.tsx
src/components/home/ThumbnailContent.tsx
src/components/inspiration/ImageView.tsx
src/constants/motions.ts
src/hooks/bridge/useAppMessage/AppMessageListener.tsx
src/hooks/bridge/useAppMessage/useAppMessage.ts
src/hooks/common/useUserAgent/useUserAgent.ts
src/pages/add/share.tsx
src/utils/common/imageDownload.ts
yarn.lock

⚠️ https://github.com/depromeet/ygtang-app/pull/119 가 배포된 후 머지되어야 합니다
기존 `light` 모드로 적용할 시 아이콘의 색상이 `gray05`로 고정되었는데,
`light` 모드일 시 `colorType='light'` 이면 `background`로, `colorType='dark'`이면 `gray05`로 적용되는 것이,
더 직관적일 것 같아 수정했어요
<br />
사용되는 곳마다 선언되고 있던 style을 모듈화했어요
<br />
줌과 이동을 위해 도현님께서 말씀해주신 `react-quick-pinch-zoom` 라이브러리를 사용했어요
https://github.com/depromeet/ygtang-client/blob/546d828bfece59b32c75ad1159212a60b0f0bef7/src/components/common/ImageContent.tsx#L121-L122
해당 부분의 overflow 속성이 고정되어 있어, 
[추가한 후 PR](https://github.com/retyui/react-quick-pinch-zoom/pull/56) 해봤는데 className을 이용해 확장 가능하다는 답변을 받았는데 이상하게도 적용되지 않더라구요
추가적인 확인 후 리팩토링 가능할 거 같아요
<br />
모바일 환경일 시 `href`에 `s3 url`을 넣어 RN에서 확인 후 저장할 수 있도록 적용했고,
이 외의 환경일 시 blob화하여 저장할 수 있도록 적용했어요
<br />
- 기존 App 에서는 `type`으로 정의되어있던 RawData가 …

이미지 저장 개발, AppMessage 관련 인터페이스 수정, IconButton 인터페이스 수정

---

src/components/common/ImageContent.tsx

앱 환경에서 opened Image가 클릭 이전에 보이지 않는 문제를 해결(시도) 합니다
> 로컬 시뮬레이터에서는 정상적으로 동작하는데... `z-index`값이 동일해서 발생하는 문제인지... 일단 머지 후 확인을 해볼 수 있을거 같아요

전체보기 이미지 z-index 값 수정

---

src/components/common/ImageContent.tsx

#480 의 3번째 시도입니다 ....
css의 문제는 아닌 것으로 파악되어 `framer-motion`의 layout 애니메이션이 다음 후보가 되어 .. 걷어내봤어요
> 이것도 아니면 `QuickPinchZoom`이 문제일 거 같아요...!

전체보기 이미지 layout 트랜지션 삭제

---

src/components/common/ToastSection.tsx
src/styles/Theme/Theme.ts

Toast 메세지 배경 색상 변경

---

src/components/home/FilterBottomSheetModal/InspirationKindSection.tsx

iOS 환경에서 flex 요소들이 예상치 못하게 나오는 환경을 대응했어요
> 시뮬레이터로 실행해 보아도 재현이 되지 않아 예상되는 것들로 대응해 봤어요
- `<span />` 태그를 `<div></div>` 태그로 수정
- `flex` 요소에 `justify-content` 속성 추가

iOS 환경 영감 종류 필터링 디자인 에러 수정

---

src/components/inspiration/ImageView.tsx
src/components/inspiration/InspirationTime.tsx
src/components/inspiration/LinkView.tsx
src/components/inspiration/TextView.tsx
src/components/inspiration/type.ts

- 영감의 `updatedDatetime`을 주입받아 시간 형태로 렌더링하는 `InspirationTime` 컴포넌트를 개발, 적용했어요.
- `ImageView`, `TextView`, `LinkView`에서 국지적으로 선언되고 있던 props의 타입을 정의하고 확장하는 형태로 리팩토링했어요. c44b1df03056622ce6b59bd8e6608d85ede03065
- https://developer.mozilla.org/ko/docs/Web/HTML/Element/time
closes #494

영감 조회시 생성 (업데이트) 시간 적용

---

src/utils/validator.ts

- `.academy`처럼 긴 surfix가 인식되지 않는 문제를 해결합니다.

url surfix의 인식 범위를 2~9으로 늘림

---

src/components/common/ToastSection.tsx
src/components/home/ClipboardAppMessageListener.tsx
src/hooks/bridge/useAppMessage/useAppMessage.ts
src/pages/add/link.tsx
src/pages/add/text.tsx
src/pages/index.tsx
src/store/Toast/toastStates.ts
src/store/Toast/useToast.ts
src/utils/validator.ts

기존 토스트 섹션에서 클립보드용 토스트를 추가했습니다. 클립보드 앱 메시지 리스너는 홈 화면에만 들어갑니다.
기존 url validator로는 다양한 상황에서 텍스트 영감을 링크 영감 타입으로 처리할 가능성이 높습니다. https로 시작해야만 링크 영감으로 분류되도록 했습니다.

clipboard로 영감 추가하기 기능

---

src/hooks/api/inspiration/useInspirationMutation.ts
src/hooks/common/useDataShareMessage.ts
src/pages/add/image.tsx
src/pages/add/link.tsx
src/pages/add/text.tsx

- 예전 '완료'로 작업되어 닫히던 코드가 사라지고 CTA버튼으로 바뀌면서 대응하지 않았던것을 적용했습니다.
- ios 일경우에만, 닫히면 됨으로 ios + share 상태인지 인지할 수 있도록했습니다.
- 이후, ios + share 상태라면 completeMessage를 보내어 app에서 메시지를 통해 앱을 종료할 수 있도록했습니다.
- 바로 닫히면 십버그같아서 1초의 delay를 주었습니다.
연관 이슈 : https://github.com/depromeet/ygtang-app/issues/122
ios 배포 이후 동작되는 코드입니다. 따라서 심사제출 시점에 머지되면 될것 같습니다!
https://user-images.githubusercontent.com/59507527/212136047-5ff8fb41-06ac-4cbd-ac3e-34b5e4bbadfb.mov
중복 되는 코드를 최대한 줄이고자 otherAction이라는 param을 받는 함수를 만들어 처리를 했습니다.
param 이름이 참...별로인듯
```ts
const requestCompleteMessageWhenIosShare = (otherAction: VoidFunction) => {
if (isIosShareView) {
setTimeout(() => {
sendShareCompleteMessage();
}, 1000);
} else {
otherAction();
}
};
```
x

모바일 공유하기 이후, 자동 닫히기

---

src/components/common/TextField/MemoText.tsx
src/components/inspiration/TextView.tsx
src/pages/content/index.tsx

- close #497 
- 글자 영감 조회 시 변경된 디자인을 적용했어요
- 모든 종류의 영감의 메모 영역에 변견된 디자인을 적용했어요
- `/content`에서 일러스트 다이얼로그를 dynamic import 했어요

글자 영감과 메모 스타일 변경

---

package.json
src/hooks/common/useIntersectionObserver/useIntersectionObserver.ts

- useIntersectionObserver에 작성되어 있는 useEffect 훅의 의존성에 의해서 발생하는 문제였습니다. 다만 올바른 수정인지는 의논이 필요해요.

무한 스크롤이 2번 실행되는 문제 해결

---

src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
src/hooks/api/inspiration/useInspirationMutation.ts

- 기존 query를 reset하던 행동에서, refetch하는 행동으로 바꿨습니다
> reset은 아예 캐싱된 값을 비워 `리스트 > 추가or삭제 >  없음 > 리스트` 임에 반해
>
> 바꾼 동작은 `리스트 > 추가or삭제 > 리스트 > 조회가 다 되면 > 리스트를 업데이트`해서 사용자 경험이 더 좋을 거라 생각했어요
- `invalidate`를 사용하지 않은 이유
- 유효하지 않음을 표기하는 `invalidate`는 `사용자가 필요하게 될 때` 다시 조회해서 더 효과적이라고 공식 문서에서 말하고 있어요
- 근데 저희는 `route as modal` 방법이라 그런지... (추측) 생성 시에는 `사용자가 필요하게 될 때`라고 판단하지 않는 거 같아요
- 코드를 읽기 힘들어지는 거 같기도하고 .. 다른 방법으로 마이그레이션해봐도 ... 좋을듯 합니다
https://user-images.githubusercontent.com/26461307/225591138-48fbe4a6-65f3-4e32-a584-c25cd2c94472.mov
https://user-images.githubusercontent.com/26461307/225587156-d3e74d68-827f-431b-b4dd-121919c75a6e.mov

영감 삭제, 추가 시 로드 로직 변경

---

src/components/common/Skeleton/Container.tsx
src/components/common/Skeleton/Thumbnail.tsx
src/components/common/Skeleton/index.tsx
src/pages/index.tsx
src/styles/Theme/Theme.ts

영감리스트에 스켈레톤을 통해서 로딩상태를 볼 수 있도록했습니다.
그를 위해 `SkeletonContainer`, `SkeletonThumbnail` 2가지 컴포넌트를 만들었습니다.
`SkeletonContainer`는 Skeleton의 content들을 감싸며 그위에 shine 에니메이션을 보여주기위한 작업이 되어있습니다.
큰하나의 shine 에니메이션으로 한 요소의 전체로 뿌려주기위해 위와같은 방식을 채용했습니다.
`SkeletonThumbnail`은 말그대로 Thumbnail의 Skeleton입니다.
https://user-images.githubusercontent.com/59507527/228573961-c71d7009-55cb-45bc-b47a-b1d4f053e75c.mov
```tsx
function SkeletonThumbnail() {
return (
<SkeletonContainer backgroundColorName="gray03"> // SkeletonContainer는 이런식으로 적용할 수 있습니다.
<div css={contentSkeletonCss}></div>
<div css={tagListSkeletonWrapper}>
<small css={tagSkeletonWrapper('sm')}></small>
<small css={tagSkeletonWrapper('lg')}></small>
<small css={tagSkeletonWrapper('md')}></small>
<small css={tagSkeletonWrapper('sm')}></small>
</div> …
```

영감리스트 다음페이지 로딩 스피너 추가 스캘래톤 버전

---

src/hooks/api/inspiration/useCheckLinkAvailable.ts

기존 서버에서 data를 형태의 error를 뱉는것에서 error가 직접적으로 throw되도록 dev서버에서 변경됨에따라 
error상황일 경우, toast message를 보여주도록 변경했습니다.
혜성님 리뷰보고 히스토리를 다시파악했습니다! 확인결과 
```ts
// .../src/hooks/api/inspiration/useCheckLinkAvailable.ts
// 여기서 https로 시작되지만 에러가 나면 if문에 들어가지않아 true로 바꾸지못해 무한 req
if (isFetchedWith.current.https === false && link.startsWith('https') === false) {
isFetchedWith.current.https = true;
return `https://${link}`;
}
// 여기서 http로 시작되지만 에러가 나면 if문에 들어가지않아 true로 바꾸지못해 무한 req
if (isFetchedWith.current.http === false && link.startsWith('http') === false) {
isFetchedWith.current.http = true;
return `http://${link}`;
}
```
주석처럼 if문에 들어지못해 flag가 ture가 되지 못하는 결과로 무한 req가 발생해 getLinkWithProtocol 최하단에 아래의 코드를 추가했습니다.
```ts
const getLinkWithProtocol = (link: string) => {
...
isFetchedWith.current.http = true; …
```

링크 영감 OG 이미지 호출 시 무한 로딩

---

src/pages/index.tsx

안드로이드 크롬 테스트에서 다음페이지 트리거를 못보는 현상이 있습니다.
하단이 너무 붙어있어 트리거를 호출하지 못하는 이슈 였습니다. 따라서 하단에 약간의 공간을 두고 그만큼 트리거 요소를 올려서 observer가 볼 수 있도록했습니다.
스크린샷 아침에 첨부예정...
close #553

fix: 안드로이드 다음페이지 트리거 이슈

---

src/hooks/api/sign-up/usePatchExtraInformation.ts
src/pages/index.tsx
src/pages/signup/information.tsx

ios의 심의 결과 연령에 대한 정보를 앱에서 사용하지 않지만 수집을하고 있어
선택 안함 또는 수집을 안하는 방향중 수집을 안하는 방향으로 결정되어 개발을 진행합니다.
추가적으로 지난 스캘래톤 적용하면서 제거되었던 empty list 컴포넌트를 다시 추가했습니다.

feat: 회원가입 시 연령 선택 제거

---

src/components/common/DropdownMenu/DropdownMenu.tsx
src/components/common/TextField/TextField.tsx
src/components/signup/EmailFeild.tsx
src/pages/signup/index.tsx

기존 이메일 도메인에 대한 오류가 발생하는것을 파악하여 해당 이슈를 해결하기위해서 domain을 선택하는 화면을 추가하는 기획에 대한 결과물입니다.
`TextFeild`와 `Dropdownmenu` 컴포넌트를 이용해서 `EmailFeild`라는 컴포넌트를 구현했습니다.
`EmailFeild는 기존의 환경에서 많은 것을 변경하기 보다는 입력에따라 email을 set해주는 정도의 작업을 진행하도록했습니다.
```tsx
const email = useInput({ useDebounce: true });
const [emailError, setEmailError] = useState('');
useEffect(() => {
if (!validator({ type: 'email', value: email.debouncedValue })) {
setEmailError('올바른 이메일을 입력해주세요.');
} else {
setEmailError('');
}
}, [email.debouncedValue]);
<EmailFeild
setEmail={email.setValue}
feedback={email.debouncedValue !== '' ? emailError || <>&nbsp;</> : <>&nbsp;</>}
/>
```
마이 브레인

이메일 Input select box 추가

---

src/pages/add/tag.tsx
src/pages/edit/tag.tsx

`CreateTagDataResponseInterface`에서는 id와 content만 가지고 있어요
> 기존에는 태그 개수를 보여주지 않아서 그랬던 것으로 보여요
하지만 바뀌어진 TagType에는 `count` 필드도 추가되어서 타입 때문에 빌드가 안되는 이슈가 있었어용
> 제가 이해한게 아니라면 말씀 부탁드려요 !!
고래서 
새로운 태그를 생성할 때는 1개일테니, 1을 낙관적으로 넣어주었습니당 
> 이후에 query를 reset해서 완전 낙관적이라기보다는 구색맞추기인 거 같긴 한데 ... 
머윤님이 봐주시면 조흘거 같습니다 👍 👍

태그 추가 시 mutation 타입 맞추기

---

src/components/common/Dialog.tsx
src/constants/localStorage.ts
src/libs/api/client.ts
src/pages/login/index.tsx

- 영감탱 익스텐션의 로그인 정보를 받아와서, 사용자에게 로그인 할 것인지 묻습니다.
- `/login`에서만 동작하도록 구현했습니다. (비로그인 사용자에게만 의견 묻도록)
- 유저가 버튼을 통해 취소하는 경우, 더 이상 물어보지 않습니다. 
- 익스텐션의 로그인 정보는 3초마다 localStorage를 통해 가져옵니다.

영감탱 익스텐션 로그인 핸들링

---

src/components/my/Menu.tsx
src/constants/common.ts
src/pages/my/index.tsx

- 메뉴 텍스트 크기를 수정했습니다.
- 링크를 slashpage로 이전했습니다.
Closed #618

마이페이지 메뉴 수정

---

src/components/home/AppendTooltip.tsx

- 기존에 AppendTooltip에서 이미지 업로드를 htmlFor로 처리하는 부분을 ref click 방식으로 변경합니다.
Closed #623

클라이언트 이미지 업로드 오류 해결
