depromeet/ygtang-client

- .gitignore
- src/store/User/index.ts
- src/store/User/useUser.ts
- src/store/User/userStates.ts
- User 스토어를 만들어봤습니다
- 에디터 설정들을 .gitignore에 추가했어요
- 대부분 vscode를 사용하실탠데... 전 webstorm을 사용해서 혹시 올라가면 겹쳐질까 싶어서요!
- Recoil을 이렇게 사용하는 것이 좋을까? 싶긴 하지만 공식 도큐멘트 보고 만들어놨습니다!
> User 스토어 생성

- src/pages/_app.tsx
최대 크기를 제한하여 웹에서도 이질적으로 보이지 않게 적용했습니당
저는 작성한 부분과 같이 해당 페이지에서만 쓰는 컴포넌트를 작성하곤 했는데,
저번에 말씀 나눈 것처럼 `components`로 빼는 게 좋을까요 ??
아니면 `_app`, `_document`, `_offline`과 같은 파일들은 생략하는 규칙을 가져볼까요??
> 최대 크기 레이아웃 설정

- src/libs/api/client.ts
- src/libs/api/fetcher.ts
Ajax request, response interceptor 적용 및 baseUrl과 쿠키 값을 허용했어요!
추가적으로 `swr`에 사용할 기본적인 `fetcher`를 만들어봤어요
- get, post, del, update
```ts
import { get, post, del, put } from '~/lib/api/client' 
interface Response {
name: string;
}
get<Response>('주소');
post('주소');
del('주소'); // delete는 자바스크립트 스펙이랑 겹쳐서 이름을 지을 수 없어요!
put('주소'); //
```
- fetcher
```ts
import { fetcher } from '~/lib/api/fetcher'
const { data } = useSWR<Response>('api주소', fetcher);
```
- [SWR data fetching](https://swr.vercel.app/docs/data-fetching)
- [Typescript Parameters utillity](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype)
> Ajax client 및 fetcher 개발

- src/constants/common.ts
- src/hooks/common/useRouterGuard.tsx
#47  에 리뷰를 통해 구현되었으며, 의논에 따라 기존 HOC? 컴포넌트 방식으로 구현보다는 hooks를 통한 구현이 좋다는 의견이 있어 
hooks로 변경되어 구현하였습니다. 
주의 사항으로는 TODO에 적힌것 처럼 추후에는 store의 인증 관련 코드를 사용할 것입니다!
또한 개발에 허들이 될 것으로 예상되어 사용부는 추가하지 않았습니다. 
```
export default function App({ Component, pageProps }: AppProps) {
const { authorized } = useRouterGuard(); // 이렇게 선언하고
return (
<RecoilRoot>
<ThemeProvider theme={Theme}>
<Layout>
<GlobalStyle />
{authorized && <Component {...pageProps} />} // 사용하면 됩니다.
</Layout>
</ThemeProvider>
</RecoilRoot>
);
}
```
- #47 (연결 PR)
- https://colossal-adasaurus-103.notion.site/Router-Gard-5d9e6d09f7ed436db807f18c6c4bcd45 (개발 과정)
- https://jasonwatmore.com/post/2021/08/30/next-js-redirect-to-login-page-if-unauthenticated (대박 참고)
> Router Guard 만들기

- src/pages/add/share.tsx
- `/add/share`에 공유 핸들링용 페이지를 만듭니다.
- 이전에 #52 에서 작업한 useAppMessage를 테스트하는 핸들러를 제작하였습니다.
앱에서 테스트하여야 핸들링 테스트가 가능하기 때문에 사용 테스트는 해보지 않았습니다.
> app to web 테스트용 웹 사이트 개발 - 테스트용 페이지 생성

- .github/CODEOWNERS
코드 리뷰어를 PR 생성할 경우 넣지 않아도 자동으로 넣어지도록 하는 설정을 추가했습니다. 
Manage access에 모두 프론트팀 모두 추가해두었습니다.
> 코드리뷰어 자동 설정 추가

- src/components/common/Tag.tsx
- src/components/common/ThumbnailTag.tsx
- src/components/home/ContentThumbnail.tsx
디자인 시스템의 `Tag` `ThumnailTag` 컴포넌트를 구현했습니다.
먼저 `Tag` 컴포넌트는 delete 동작을 할 수 있도록 구현을 진행했습니다. 또한 random하게 color가 변경되는 것으로 이야기를 나누었던 것을 기억하여  구현을 해두었습니다. (시간이 나 미리 만들었을 뿐 내일 확인하여 없어질 수 있습니다.)
구현하며 높이를 고정하지 않고 padding만을 주어서 크기를 지정하려 했지만 icon이 있는 경우 28px 없는 경우 27px 이 되어서 크기 차이가 나는것보다는 28px 고정이 되는것이 맞다고 생각하여, 28px 고정하여 사용했습니다.
추후에 프로퍼티가 정해지면 props와 event가 변경될 것으로 보여 TODO를 작성해 두었습니다.
또한 Icon 적용 이전으로 Icon부분을 무늬만 만들어서 구현했으며, TODO를 작성해 두었습니다. 
`ThumnailTag`  를 구현했습니다.
`Tag` `ThumnailTag`을 처음에 하나로 구현할까 고민하였습니다. 어차피 똑같은 Tag 아닌가? 하고요 하지만 디자인을 살펴본 결과 사용처와 기능이 다르고 같이 만든다면 여러 다른 PROPS를 만들게 될 것으로 예상되어 분리해서 개발했습니다. 
**파레트를 적용하여 구현을 진행했습니다. 따라서 #65 가 머지 이후에 머지될 수 있습니다.** 빌드 fail도 해당 부분 관련으로 예상됩니다.
`ThumnailTag`  
`Tag` (해당하는 UI에서 사용되지는 않습니다.)  
```tsx
import Thumbnail from '~/components/common/ThumbnailTag'; …
```
> 공용 컴포넌트 - Tag, ThumnailTag 구현

- src/components/common/CheckList.tsx
- src/components/common/icons/ChevronIcon.tsx
- src/pages/test/index.tsx
`Check List` 공용 컴포넌트를 구현하였습니다.
1. 해당 부분에 IconButton을 사용하고 싶었지만 color 변경 및 deg 설정에 어려움 있어서 사용하지 못했습니다.
- Svg에 up | down 등으로 방향설정을 하려했지만 deg을 직접주는 방법이 더 좋지 않을까라는 생각을 했습니다. 이건 기본 < 여서 조금 애매해서요ㅜ
2. color의 경우, falsely면 기본값이 적용되지만 "currentColor"을 명시적으로 넣어줄지 고민입니다.
3. onClickChevron라고 >를 클릭했을때 event를 정의했는데 마땅히 좋은 이름이 떠오르지 않아 icon이름을 그대로 사용했습니다. 
-  예상 동작이 상세 페이지로 이동 또는 router이동 등으로 예측되지만...애매해서 위에 처럼 지었습니다.
```tsx
<button onClick={onToggle} css={IconWrapperCss}>
<CheckCircleIcon color={isChecked ? '' : theme.color.gray01} />
</button>
```
```tsx
import { useState } from 'react';
import CheckList from '~/components/common/CheckList';
export default function Test() {
const [isChecked, setCheck] = useState(false);
return (
<CheckList
id="checkbox_1"
isChecked={isChecked}
onToggle={checked => { …
```
> Check List 공용 컴포넌트 구현

- src/components/LinkThumbnail.tsx
- src/pages/test/index.tsx
- src/styles/utils/textEllipisCss.ts
LinkThumbnail 컴포넌트를 구현했습니다.
- textEllipsisCss를 구현하여 Style floder / utils에 넣어 놓았습니다.
- 혹시 다른 폴더나 이름 관련하여, 좋은 방향이 있으면 알려주세용!
- test page에 컴포넌트 간의 구분을 위하여 간단한 css작업했습니다.
- 기본적으로 LinkThumbnailMetaData 타입을 만들어서 구현을 진행했습니다.
```ts
export interface LinkThumbnailMetaData {
imageUrl?: string;
title: string;
url: string;
alt?: string;
}
```
- 아래 처럼 컴포넌트 내부에서 onDelete를 그냥 수행해도될듯한데 어떻게 생각하시나요?
```tsx
// NOTE: 추후에 API 나오면 여기서 그냥 Delete 실행
const onDelete = (event: React.MouseEvent<HTMLButtonElement>) => {
event.preventDefault();
event.stopPropagation();
};
```
- VIEW
```tsx
<LinkThumbnail
thumbnail={"Thumbnail_Object"}
/>
```
- EDIT
```
<LinkThumbnail
edit
thumbnail={"Thumbnail_Object"}
/>
```
> 공용컴포넌트 - LinkThumbnail 구현

- package.json
httpsdev 명령어가 httpsDevServer.js로 되어 있지 않고 server.js로 설정되어 있는 것을 수정합니다.
#96 에서 실수로 수정되지 않은 것 같아요.
> package.json httpsDevServer 이름 문제 해결

- src/hooks/common/useUserAgent.ts
- src/pages/test/index.tsx
다음 순서로 작업 할 Bottom CTA Button 공통 컴포넌트 제작을 위해 userAgent를 파악하는 훅을 간단하게 작성했습니다.
넥제에서 제대로 userAgent를 파악하려면 [이런 것](https://github.com/tokuda109/next-useragent)을 사용해봐도 좋겠지만..
저는 이 훅으로도 충분히 크로스 브라우징에 대응하는 데 문제 없었어요!
혹여나 나중에 필요하다면 고려를 해보시죠!
- 테스트 페이지에도 확인해 보실 수 있도록 추가해놓았어요!
- 테스트 페이지 참고해주세요!
> 공용 훅 - useUserAgent

- src/components/home/ContentThumbnail.tsx
- src/pages/index.tsx
- src/remotes/insipiration.d.ts
- src/styles/GlobalStyle/GlobalStyle.tsx
- 홈 화면에서 사용되는 썸네일에 링크 타입을 적용했어요
- openGraph response에 대한 인터페이스를 정의했어요
- firefox, ie 환경에서 스크롤바가 안보이도록 했어요
> 홈 화면 - 썸네일 - 링크 타입 개발

- src/components/common/BottomSheetModal.tsx
- src/pages/my/tag/AddTagBottomSheet.tsx
- src/pages/my/tag/index.tsx
혀바닥의 이름은 Bottom Sheet 였습니다.
- 등록 뷰에 사용되는 BottomSheetModal을 구현했습니다!
- 해당 BottomSheetModal을 이용해서 AddTagBottomSheet을 구현하였습니다.
- 아래의 코드를 통해서 백그라운드(Dim)을 클릭했을 경우, 종료되도록 구현했습니다.
```tsx
const onDeleteHandler = (e: React.MouseEvent<HTMLDivElement>) => {
if (e.target !== e.currentTarget) return;
onClose();
};
```
useDidUpdate가 원하는 시점에만 불리는게 아니여서 확인중입니당~
https://user-images.githubusercontent.com/59507527/167478915-c24e9475-8b36-4b7d-acbc-89747ba2f0fd.mov
```tsx
export interface BottomSheetModalProps {
isShowing: boolean;
children: ReactNode;
onClose: VoidFunction;
}
<BottomSheetModal
isShowing={isShowing}
onClose={() => {}}
>
{children}
</BottomSheetModal>
```
- https://material.io/components/sheets-bottom
- https://blog.mathpresso.com/bottom-sheet-for-web-55ed6cc78c00
> 마이페이지 - 테그관리 - 등록 모달 (BottomSheetModal)

- src/constants/common.ts
- src/hooks/api/member/useMemberLoginMutation.ts
- src/hooks/api/reissue/useReissueMutation.ts
- src/libs/api/client.ts
- src/pages/login/index.tsx
- src/store/User/UserProvider.tsx
- src/store/User/useUser.ts
- reissue 쪽의 변경된 뮤테이션을 수정하였습니다.
- 백엔드 쪽 401 에러가 발생하는 부분은 아직 수정되지 않아서, 백엔드분들에게 요청드려놨습니다. 수정되면 아마 정상 작동할 것으로 사료됩니다.... 아마....
- 로그인 후 리프레시 토큰 쿠키 set 로직이 누락되었던 점 수정하였습니다.
- 로그인 성공 이후 아무런 액션이 생기지 않던 부분을 수정하였습니다.
실제 작동에 성공하여야 하기 때문에, API 수정 전까진 머지하지 않도록 하겠습니다.
Closed #164
> 변경된 API 대응 및 reissue 인증 테스트

- src/components/common/ImageContent.tsx
- src/components/home/AppendTooltip.tsx
- src/hooks/api/inspiration/useInspirationMutation.ts
- src/libs/api/queryClient.ts
- src/pages/add/image.tsx
- src/store/UploadedImage/UploadedImgState.ts
- src/store/UploadedImage/index.ts
- src/store/UploadedImage/useUploadedImg.ts
디자이너분들이 기획해 주신 플로우 상 이미지 추가 버튼 클릭 시 바로 이미지 업로드 하는 사진이 뜨고! 사진을 클릭 했을 때 
페이지 이동이 있는  flow더라구요.
이런 부분을 구현하기 위해 appendTooltip에 이러저러한 코드들이 추가되었습니다..! 
아이폰으로 확인했을 때에도 사집 업로드 기능으로 연결되는 것 확인했습니다. (대윤님 땡큐!)
- TODO: 가끔 이미지가 제대로 업로드 되지 않을 때 add/image로 페이지 이동하지 않는 에러가 발생하는 것 같아요. 이부분은 다음 이슈에서 처리하도록 할게요!
위와 같은 flow를 구현하기 위해 uploaded Image를 전역으로 관리하게 되었어요.
file을 base64로 변경해서 recoil을 사용해서 /add/image로 넘겨주었습니다.
혜성님이 태그 작성해주신 것 참고했고, 저도 추후에 태그랑 똑같은 방향으로 crud 구현할 것 같아요!
다만... 궁금한 점은 제가 영감 추가를 했을 때 메인 페이지로 돌아가면서 방금 추가한 영감이 보여야 하는데요,
그 메인페이지에서 리스트를 받아오는 엔포가 `get<TagResponseInterface>(`/v1/tag/list?size=20&page=${page}`);` 이게 맞나요? 
invalidate 시켜야 하는 엔포가 정확하지 않아서 아직 적용시키진 못했어요!
디벨롭 상태에서는 굳이 retry를 3번까지 할 필요가 없는 것 같아서 설정했고요..
저희 무한 스크롤로 구현된 어플 특성상, 어플이 쉽게 mount되거나 window focus 등으로 새롭게 fetch되어서 스크롤이 올라가는 현상을 방지하기 …
> 영감 추가 - 이미지 API 연결

- src/hooks/api/inspiration/useInspirationMutation.ts
- src/pages/add/image.tsx
- src/pages/add/link.tsx
- src/pages/add/text.tsx
> 영감 추가 - 텍스트, 링크 API 연결

- src/components/common/NavigationBar/NavigationBar.tsx
- src/components/common/Spinner/FixedSpinner.tsx
- src/components/home/AppendButton.tsx
- src/components/home/AppendTooltip.tsx
- src/components/home/HomeNavigationBar.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- iOS 환경에서 input을 클릭할 시 zoom in 되는 문제를 막기 위해 메타 태그를 추가했어요 
- 자세한 사항은 아티클 확인하시면 좋을 거 같아용 https://devsoyoung.github.io/posts/ios-input-focus-zoom/
- 홈 화면에서 z-index 관련 이슈를 해결했어요
- 홈 화면 appendTooltip에서 border-bottom 이슈를 해결했어요
> 홈 화면 z-index, iOS input zoom in 수정

- src/hooks/common/useImgUpload.ts
- src/pages/add/image.tsx
- src/store/UploadedImage/UploadedImgState.ts
- src/store/UploadedImage/useUploadedImg.ts
[fix: add image blob 타입으로 변경하여 에러 해결](https://github.com/depromeet/11th_7team_web/commit/8f818f31f3cc932b3b3ceac37e9886c7a36c0280)
base64 형태로만 관리하던 이미지를 blob 타입을 추가하면서 fetching error를 해결했습니다.
> 영감 추가 - 이미지 base64에서 blob 타입으로 변경 관리

- src/components/LinkThumbnail.tsx
- src/components/add/LinkInput.tsx
- src/hooks/api/inspiration/useCheckLinkAvailable.ts
- src/pages/add/link.tsx
- src/pages/test/index.tsx
[feat: link 영감 추가 시 openGraph api 연결 추가](https://github.com/depromeet/11th_7team_web/commit/51589a33ee547e624811eab0901311ff610a445d)
> 영감 추가 - 링크 타입 영감 검증 api 연결 추가 

- src/store/User/UserProvider.tsx
> UserProvider 로딩 처리 / 리프레시 토큰 오류 핸들링

- src/pages/login/index.tsx
- src/pages/signup/email-verified.tsx
- src/pages/signup/index.tsx
> 로그인 폼 - 입력 안했을 때 체크 떠있는 문제

- src/components/add/AddTagFormRouteAsModal.tsx
- src/components/add/LinkInput.tsx
- src/components/home/Thumbnail.tsx
- src/components/inspiration/ImageView.tsx
- src/components/inspiration/InspirationViewAsModal.tsx
- src/components/inspiration/LinkView.tsx
- src/components/inspiration/TextView.tsx
- src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
- src/pages/content/[contentId].tsx
- src/pages/index.tsx
- src/store/Inspiration/InspirationDetailState.ts
- src/store/Inspiration/index.ts
- src/store/Inspiration/useInspirationDetail.ts
[feat: 영감 상세보기 화면 추가](https://github.com/depromeet/11th_7team_web/commit/1b0aa58c9ae7750df4dde656694a4f6a0795864c)
> 영감 보기 - 텍스트, 링크, 이미지 타입 영감 상세 보기

- src/components/home/Thumbnail.tsx
- src/components/inspiration/ImageView.tsx
- src/components/inspiration/LinkView.tsx
- src/components/inspiration/TextView.tsx
- src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
- src/pages/index.tsx
- src/store/Inspiration/InspirationDetailState.ts
- src/store/Inspiration/useInspirationDetail.ts
> 영감 상세보기 메모 보기 기능 추가

- src/components/inspiration/ImageView.tsx
- src/components/inspiration/LinkView.tsx
- src/components/inspiration/TextView.tsx
> 영감 상세 보기 submit 버튼 삭제

- src/hooks/api/inspiration/useInspirationMutation.ts
- src/pages/content/[contentId].tsx
[feat: inspiration 삭제 기능 추가](https://github.com/depromeet/11th_7team_web/commit/aa8116acdc22e7d2dca7d70d4c1082bfb397904e)
추후 다이얼로그 추가해서 삭제 여부 확인하는 기능 추가 필요합니다.
> 영감 삭제 기능 추가

- src/hooks/api/reissue/useReissueMutation.ts
- src/pages/login/index.tsx
- src/pages/signup/email-verified.tsx
- src/pages/signup/index.tsx
- src/store/User/UserProvider.tsx
- 리프레시 갱신 오류를 해결합니다.
- debouncedValue 적용으로 인해 체킹이 늦은 문제를 해결합니다.
> 리프레시 토큰이 올바르지 않을 때 갱신이 되지 않는 문제 & debounce 인풋 체킹 문제

- jest.config.js
#243 에 작성한 것처럼 커버리지 디렉토리를 수정했어용
> 테스트 커버리지 디렉토리 수정

- src/hooks/api/member/useMemberLoginMutation.ts
- src/hooks/api/reissue/useReissueMutation.ts
- src/remotes/auth.d.ts
- 이전 회의에서 잠깐 말씀드렸던 #169 를 수정하였습니다.
Closed #169
> ResponseInterface에서 data 구조 사용 안하도록 수정

- src/components/my/Profile.tsx
- src/store/User/UserProvider.tsx
- src/store/User/useUser.ts
> 마이페이지 - 로그아웃

- src/components/common/SnapCarousel/index.test.tsx
- src/components/common/SnapCarousel/index.tsx
- src/components/onboard/index.tsx
- src/libs/ga/index.test.ts
- src/libs/ga/index.ts
- src/styles/utils/index.ts
- Wildcard export로 되어있던 부분을 Named export로 수정하였습니다
- 그에 따른 테스트 코드 확인 및 보강 하였슴니다
> wildcard export를 named export로 수정

- src/constants/common.ts
- src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
- src/hooks/api/auth/useCheckPasswordResetEmailVerifiedMutation.ts
- src/hooks/api/auth/useSendPasswordResetEmailMutation.ts
- src/hooks/api/member/useSendResetPasswordMutation.ts
- src/hooks/common/useInternalRouter.ts
- src/pages/password/index.tsx
- src/pages/password/sent-email.tsx
- src/pages/password/update/[token].tsx
- src/pages/password/verified.tsx
- 비밀번호 찾기를 구현했습니다.
- 관련된 api 스펙 mutation을 추가했습니다.
> 비밀번호 변경 테스트 완료되었습니다!
<!--
리뷰어
혜성 : hyesungoh
도현 : ddarkr
대윤 : SenseCodeValue
은정 : positiveko
--
> 로그인 / 회원가입 - 비밀번호 찾기

- src/components/add/LinkInput.tsx
- src/components/common/Content/TagContent.tsx
- src/components/common/ImageContent.tsx
- src/components/common/TextField/Input.tsx
- src/components/common/TextField/MemoText.tsx
- src/components/common/TextField/TextField.tsx
- src/components/inspiration/ImageView.tsx
- src/components/inspiration/LinkView.tsx
- src/components/inspiration/TextView.tsx
- src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
- src/hooks/api/inspiration/useInspirationMutation.ts
- src/hooks/common/useInternalRouter.ts
- src/pages/add/image.tsx
- 영감 수정 (이미지, 링크, 텍스트) 기능 추가했습니다. 
- 영감 태그 수정 기능은 다음 풀리퀘에서 이어서 작성하겠습니다.
> 영감 수정 기능 추가

- src/components/my/tag/MyTagItem.tsx
- src/pages/add/tag.tsx
- src/pages/my/tag/AddTagBottomSheet.tsx
- src/pages/my/tag/index.tsx
- src/pages/tag/index.tsx
- 태그 리스트에 무한 스크롤을 추가하였습니다!
- FixedSpinner를 넣었지만 너무 빨리 로딩되어 안보이는것으로 보입니다! 
- 태그관리의 추가 | 삭제 API를 부착하였습니다!
- edit쪽은 은정님꼐서 작업중이셔서 추후에 작업하는것으로 하겠습니다.
1. 모달과 NavigationBar와의 z-index 문제가 있는것 같습니다!
2. `태그 추가` | `태그 필터` 페이지의 하단이 바닥과 너무 붙어있어서 pdding값을 주는것을 의논해야될 것 같습니다!
3. `Menu` | `Tag` 컴포넌트에 motion 추가하겠숩니당!
https://user-images.githubusercontent.com/59507527/169693113-45cdb258-0ca9-411f-83fd-1ea2351e7cbd.mov
https://user-images.githubusercontent.com/59507527/169693292-5a93280b-733d-46ae-a2e6-2003e9930b0a.mov
> 태그 리스트 무한 스크롤 & 태그 관리 API 추가 (#238, #179)

- src/hooks/api/auth/useSignupSendEmailMutation.ts
- 회원가입 이메일 전송 엔드포인트 변경 사항을 반영합니다.
> 회원가입 이메일 엔드포인트 수정

- src/components/my/Profile.tsx
- src/hooks/api/member/useGetUserInformation.ts
- src/hooks/api/member/useGetUserInfromation.ts
- src/hooks/api/member/useUserInformationMutaion.ts
- src/hooks/common/useInternalRouter.ts
- src/pages/my/account/change-nickname.tsx
- src/pages/my/account/change-password.tsx
- src/pages/my/account/index.tsx
- src/remotes/member.d.ts
- src/store/UserInformation/index.ts
- src/store/UserInformation/useUserInformation.ts
- src/store/UserInformation/userInformationStates.ts
- 유저 정보 API를 부착했습니다.
- 유저 정보를 recoil로 관리 합니다.
- 닉네임 변경 페이지를 개발하였습니다.
`userInformation` 같은 경우, 예~~전에 recoil로 관리하자는 이야기와 그렇게하는게 편할것 같아 개발을 했습니다.
이때, 제가 recoil에 refetch부분을 정의했는데 이것을 mutation onsuccess에 사용하는게 맞나? 각각인데 의존성을 갖는것 같아 따로 진행을 했습니다.
```ts
// ...( recoil) store/UserInformation/useUserInformation.ts
export function useUserInformation() {
const [userInformation, setUserInformation] = useRecoilState(userInformationState);
const { refetch } = useGetUserInformation(setUserInformation);
return {
userInformation,
refetchUserInformation: refetch,
};
}
// ...(react-query/mutation) api/member/useUserInformationMutaion.ts
// 그냥 resetQueries 사용하기
const reSetUserInformation = () => {
queryClient.resetQueries(USER_INFORMATION_QUERY_KEY);
};
// 아니?! recoil에서 받아 사용하기
const { refetchUserInformation } …
```
> 마이페이지 - 유저 정보 API 연결 (#240)

- .eslintrc.js
- .github/workflows/CI.yml
- .gitignore
- cypress.json
- cypress/fixtures/example.json
- cypress/integration/1_before_login/onboard.ts
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- yarn.lock
- Cypress를 설치 및 테스트 코드를 작성할 수 있는 환경을 구성했어요
- CI 시 Cypress가 실행될 수 있도록 구성했어요
- PR에 코멘트도 달아줘요
> E2E 테스트 환경 및 CI 구성 w/ Cypress

- .github/ISSUE_TEMPLATE/test.md
- cypress.json
- cypress/integration/1_before_login/onboard.ts
- onboard route의 e2e 테스트 코드를 작성했어요
- 테스트 issue 템플릿을 추가했어요
> onboard route E2E 테스트 코드 작성

- src/hooks/api/member/useChangePassword.ts
- src/pages/my/account/change-password.tsx
- src/pages/my/password.tsx
마이페이지의 기능인 비밀번호 변경 기능을 작업했습니다. 디자인이 기능 스펙에 맞게 나와 있지 않은 것 같아 따로 요청드렸어요.
비밀번호가 변경되면서 마이페이지/내 계정으로 바로 이동됩니다.
> 마이페이지 - 비밀번호 변경

- src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
- 이메일 인증 완료 url이 바뀌어서 해당 url을 반영합니다.
> 이메일 인증 완료 체크 api 주소 변경

- src/components/common/CheckList.tsx
- src/pages/signup/email-verified.tsx
- src/pages/test/index.tsx
- `CheckList` 컴포넌트가 외부링크로 갈 수 있도록 기능을 추가했습니다.
- 해당 컴포넌트는 오로지 회원가입의 정보 제공을 위해서만 사용되어서 `externalHref` 받아서 이동되도록 설계했습니다.
- 개인정보 정책 | 이용약관 노션 링크 연결했습니다.
```tsx
<CheckList
isChecked={checkTerms}
externalHref={POLICY_URL.TOS}
onToggle={() => setCheckTerms(!checkTerms)}
>
```
> 회원가입 - 개인정보 정책 | 이용약관 노션 링크 연결

- src/components/common/TextField/Input.tsx
https://gahyun-web-diary.tistory.com/210
해당 이슈를 수정합니다. 다만 iOS 구버전 테스트가 어려워서 확인해보진 못했어요 ㅠㅠ
> 텍스트 필드에 그림자 생기는 현상

- src/pages/my/account/change-password.tsx
- 비밀번호의 조건이 잘못 구성되어 있는 문제를 해결합니다.
Closed #320
> 비밀번호 변경 - 인증 조건에 맞는데도 불구하고 처리 안되는 문제 수정

- src/components/common/Button/Button.test.tsx
- src/components/common/Button/CTABottomButton.test.tsx
- src/components/common/Button/CTAButton.test.tsx
- src/components/common/Button/FilledButton.test.tsx
- src/components/common/Button/GhostButton.test.tsx
- src/components/common/Button/index.test.tsx
- Button과 하위 컴포넌트들의 테스트 코드를 작성해봤어요
- 현재 테스트 환경에서 emotion css가 동작하지 않아, 스타일링 테스트는 작성하지 못했어요
> Button 컴포넌트 테스트 작성

- src/pages/my/account/change-nickname.tsx
- src/pages/my/account/index.tsx
- src/pages/my/index.tsx
- 기존 빈 문자열과 이전 닉네임과 비교하는 로직에 추가적으로 4자 이상, 20자 이하 로직을 더했어요
- 훅을 이용해 관심사를 분리하려 노력했어요
- TestFlight 환경에서는 빈 문자열도 에러를 발생하지 않았는데, 로컬 시뮬레이터 환경에서는 정상적으로 에러가 발생되더라구요. 재배포 후 확인해봐야할 거 같아요
> 닉네임 변경 조건 추가 및 리팩터링

- src/components/add/AddTagFormRouteAsModal.tsx
- src/components/common/PortalWrapper.tsx
- src/components/edit/EditTagFormRouteAsModal.tsx
- src/components/home/TagFormRouteAsModal.tsx
- src/components/inspiration/InspirationViewAsModal.tsx
- src/pages/_app.tsx
- src/pages/_layout.tsx
_layout.tsx로 레이아웃 컴포넌트 분리했고, safe-area 적용했습니다.
모달에도 적용하면서 리팩터링을 했어요. 
리액트 네이티브 시뮬레이터로 ios 환경에서는 제대로 적용되는 것 확인했는데요, Android 확인이 필요합니다 :) 부탁드려요 도현님! @ddarkr
> layout 모듈화 및 webview safe-area 적용

- src/pages/login/index.tsx
- (회의에서 브리핑 드렸던 이슈) 비밀번호 찾기 버튼을 누르면 페이지로 넘어가도록 연결합니다.
> 로그인 페이지 비밀번호 찾기 링크 연결

- src/pages/_layout.tsx
- src/pages/add/image.tsx
- src/pages/add/link.tsx
- src/pages/add/text.tsx
- src/styles/utils/viewHeight/viewHeight.ts
[100vh 적용 오류 해결](https://github.com/depromeet/11th_7team_web/commit/086d61be2eca47be68cab9425247397849ad14dc)입니다.
#353 #355 이슈를 해결했습니다.
> 100vh 적용 오류 해결

- README.md
App Store Marketing Tools (https://tools.applemediaservices.com/app-store) 을 이용하여 링크를 만들어 추가했습니다.
> App Store 링크 추가

- src/components/home/ThumbnailContent.tsx
Closed #368 
QA에 올라온 링크 섬네일 안뜨는 문제를 해결합니다.
useDidMount를 사용해서 src가 업데이트 되지 않아 발생하는 문제였어요!
> 홈화면 링크 썸네일이 표시되지 않는 문제

- src/components/add/ImgUploader.tsx
- src/pages/add/image.tsx
- src/pages/add/link.tsx
- src/pages/add/text.tsx
안드로이드에서 heic 업로드로 인한 이미지 에러를 해결합니다.
iOS에서 테스트 완료입니다!
> 업로드 가능 이미지 포맷 heic 제거

- src/components/home/ThumbnailContent.tsx
- 패치 후에도 프로덕션에선 썸네일이 안나오는 이슈를 해결합니다. (useDidUpdate 이슈인 것 같아서 변경했습니다)
Closed #379
> 홈 화면 링크 섬네일 계속 안보이는 문제

- README.md
레포 이름을 바꾸면서 뱃지랑 설정 꼬인 걸 풀었어요
> 설정 꼬인 걸 풀지 않아서 PR에 댓글을 안남겨주는 거였더라구요!
> 리드미 codecov 뱃지 링크 업데이트

- README.md
> README 링크 수정

- src/components/common/ImageContent.tsx
> image content max height 제한 제거 및 min height 수정

- src/components/add/LinkInput.tsx
- src/components/common/UserProvider/UserProvider.tsx
- src/components/my/tag/MyTagItem.tsx
- src/hooks/api/inspiration/useInspirationMutation.ts
- src/hooks/api/member/useMemberSignOutMutaion.ts
- src/hooks/api/member/useUserInformationMutaion.ts
- src/hooks/api/sign-up/useSignupMutation.ts
- src/pages/add/image.tsx
- src/pages/add/link.tsx
- src/pages/add/text.tsx
- src/pages/edit/tag.tsx
- src/pages/login/index.tsx
- src/pages/my/tag/AddTagBottomSheet.tsx
- src/pages/password/index.tsx
- src/pages/password/verified.tsx
- src/pages/signup/email-verified.tsx
- src/pages/signup/index.tsx
- src/pages/signup/sent-email.tsx
- src/store/AppliedTags/useAppliedTags.ts
노션에 작업된 사항에 따라 토스트 메세지 문구를 수정했어요 !
> 더블, 트리플 체크해보았어요 !
> 토스트 메세지 문구 수정

- src/components/add/ImgUploader.tsx
- src/components/common/ImageContent.tsx
- src/pages/add/image.tsx
- design: image content box css 수정했고, image height가 짧은 경우 하단에 백그라운드가 생기는 현상 방지.
- feat: ios, android에서 이미지 공유하기로 영감 추가 기능을 개발하기 위해 리다이렉트 룰을 pc에만 제한 적용. 추후 기능 개발 완료되면 검토 필요
- fix: heic, heif 포맷 업로드 방지 추가
> add/image에서 redirect를 pc 한정 적용하도록 변경

- src/pages/signup/information.tsx
서버에서 제공해주는 지표외에 믹스패널에서도 추가적으로 확인할 수 있도록 `성별`, `나이`, `관심 직군`에 대해 이벤트를 부착했어요
> 요 PR 적용 이후에 리팩토링해볼게요!
closed #436
> 사용자 추가 정보 이벤트 부착

- src/pages/add/image.tsx
- isDesktop가 함수여서 함수를 실행시키도록했습니다.
```diff
diff --git a/src/pages/add/image.tsx b/src/pages/add/image.tsx
index cf4457e..656f013 100644
--- a/src/pages/add/image.tsx
+++ b/src/pages/add/image.tsx
@@ -44,7 +44,7 @@ export default function AddImage() {
});
useEffect(() => {
-    if (!uploadedImg && isDesktop) push('/');
+    if (!uploadedImg && isDesktop()) push('/');
}, [uploadedImg, push, isDesktop]);
const { tags } = useAppliedTags(true);
```
> add/image isDesktop 채크 오류 해결하기

- src/components/home/AppendButton.tsx
- src/components/home/AppendTooltip.tsx
- src/pages/_app.tsx
- src/styles/GlobalStyle/GlobalStyle.tsx
- src/styles/utils/viewHeight/viewHeight.ts
- safe area 웹 적용 원복: app으로 safe-area를 적용하고 웹에 적용했던 부분은 취소합니다.
- https://github.com/depromeet/ygtang-app/pull/80
> safe area 웹 적용 원복

- src/hooks/common/useDataShareMessage.ts
- src/pages/add/image.tsx
- src/pages/add/link.tsx
- src/pages/add/text.tsx
- src/utils/common/index.ts
- 전달 받은 base64 data를 가공하여 add/image에서 사용할 수 있는 형태로 만드는 작업을 진행했습니다.
- `uploadImg`의 파라미터인`{blob, base64}`에 넣을 수 있도록 base64 data를 blob으로 변경하는 작업을 진행했습니다.
- 이과정에 필요한 `base64ToBlob` 함수를 사용하였습니다.
- 영감 타입에 따라 `setStateHandler`가 달라져야 함으로 `영감 타입`을 받아서 type guard를 할 수 있도록 진행했습니다.
- 파라미터에 `type`이 추가되었습니다.
- IMAGE 영감 저장에 있어 Error가 발생하였습니다. 이는 filename에 확장자가 없어서 였습니다.
- 따라서 blob.type()으로 확장자를 지정할 수 있는 코드를 구현했습니다.
- 파일명은 최대한 겹침을 방지하기위해 timestamp를 이용하도록했습니다. (겹처도 오류는 없습니다~)
```ts
const fileExtension = uploadedImg.blob.type.replace('image/', '');
imgData.append('file', uploadedImg.blob, `image-${new Date().getTime()}.${fileExtension}`);
// ex) image-2313213231.jpeg
``` 
https://user-images.githubusercontent.com/59507527/174472424-828538f7-dc51-418b-9e84-de5e28b0041f.mov
```ts
interface …
```
> 영감 공유하기 - IMAGE

- src/components/home/AppendButton.tsx
- src/components/home/AppendTooltip.tsx
- src/pages/_app.tsx
- src/styles/GlobalStyle/GlobalStyle.tsx
- src/styles/utils/viewHeight/viewHeight.ts
앱 배포 전까지 임시로 safe-area를 적용합니다.
> safe area 웹 임시 적용

- src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
> 영감 조회 크기 변경

- src/components/common/NavigationBar/NavigationBar.tsx
- src/components/common/TextField/Input.tsx
- src/components/common/TextField/TextField.tsx
- src/components/common/icons/ChevronIcon.tsx
- src/pages/add/text.tsx
design: input disabled된 input 글자색 에러 해결
> input disabled된 input 글자색 에러 해결

- src/components/home/AppendButton.tsx
- src/components/home/AppendTooltip.tsx
- 이전 작업 시에 safe-area가 제거되어 낮아보이는 문제를 해결합니다. 고정 70px로 맞췄습니다.
https://www.notion.so/depromeet/679bde61b46d4ff3b7a6854dfb8aa690
> 영감 추가버튼 위치 조정

- public/.well-known/apple-app-site-association
- public/.well-known/assetlinks.json
유니버셜, 딥 링크 인증을 위해 두 파일을 작성했어요
- apple-app-site-association
- assetlinks.json
- https://rhammer.tistory.com/261
- https://zetal.tistory.com/entry/iOS-%EC%9C%A0%EB%8B%88%EB%B2%84%EC%85%9C-%EB%A7%81%ED%81%AC-%EC%A0%81%EC%9A%A9-%EB%B0%A9%EB%B2%95-Universal-Link
> 유니버셜 링크, 딥 링크를 위한 인증 파일 게시

- src/hooks/api/inspiration/useInspirationMutation.ts
UX writing에 따라 태그 추가, 삭제 시 토스트 메세지의 `!`를 `.`으로 수정했어요
> 태그 추가, 삭제 시 토스트 메세지 수정

- .github/ISSUE_TEMPLATE/refactor.yml
이슈 템플릿 중에 `issue-form`이란 형태가 있더라구요
저희 템플릿 중에 `refactor` 라벨에 대한건 아직 없어 만들어보았슴다
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
> refactor 이슈 템플릿 추가

- src/components/common/ImageContent.tsx
저번 PR(#480)과 동일하게 전체보기 이미지에서 처음에 보이지 않는 문제를 수정(시도)합니다 ㅠ
시뮬레이터, 사파리 브라우저 등에서도 확인하고 있는데 똑같은 이슈 재현이 안되네요 ㅠㅜ
> 전체보기 이미지 transform-origin 속성 설정

- README.md
> readme owner에 해성님 추가

- src/components/common/TextField/Input.tsx
- src/components/common/TextField/TextField.tsx
- src/pages/login/index.tsx
- src/pages/signup/email-verified.tsx
- src/pages/signup/index.tsx
- src/styles/Theme/Theme.ts
- `Theme`에 `alert` 색상을 추가했습니다
- ~~`Input`과 `TextField`의 `border` 색상, `feedback` 메세지 색상을 `alert` 색상으로 적용하였습니다.~~
- `Input`의 props에 `alertWhenFocused`를 추가했어요. optional `boolean` 타입으로 주입 시 `border` 색상을 `alert`로 합니다.
- `TextField`도 마찬가지로 `feedback` 메세지 색상을 `alert`으로 적용하도록 했어요
closes #493
> Alert 색상 추가 및 적용

- .github/workflows/CI.yml
CI 단계에서 아래 라이브러리를 사용해
번들링 사이즈를 시각적으로 보여줄 수 있도록 해봤어요
https://github.com/transferwise/actions-next-bundle-analyzer
closes #500
> actions-next-bundle-analyzer 적용

- src/pages/password/index.tsx
- 비밀번호 찾기 과정 중 이메일 발송 시 로딩 스피너를 띄웠어요
closes #503
> 비밀번호 찾기 이메일 발송 시 로딩 스피너 렌더링

- package.json
- src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
- src/hooks/api/auth/useCheckPasswordResetEmailVerifiedMutation.ts
- src/hooks/api/auth/useSendPasswordResetEmailMutation.ts
- src/hooks/api/auth/useSignupSendEmailMutation.ts
- src/hooks/api/inspiration/useCheckLinkAvailable.ts
- src/hooks/api/inspiration/useGetAllInspirations.ts
- src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
- src/hooks/api/inspiration/useInspirationById.ts
- src/hooks/api/inspiration/useInspirationMutation.ts
- src/hooks/api/member/useChangePassword.ts
- src/hooks/api/member/useGetUserInformation.ts
- src/hooks/api/member/useMemberLoginMutation.ts
- src/hooks/api/member/useMemberSignOutMutaion.ts
- src/hooks/api/member/useSendResetPasswordMutation.ts
- src/hooks/api/member/useUserInformationMutaion.ts
- src/hooks/api/reissue/useReissueMutation.ts
- src/hooks/api/sign-up/useCheckExistsNicknameMutation.ts
- src/hooks/api/sign-up/usePatchExtraInformation.ts
- src/hooks/api/sign-up/useSignupMutation.ts
- src/hooks/api/tag/useGetTagListWithInfinite.ts
- src/hooks/api/tag/useTagMutation.ts
- src/hooks/api/tag/useTagRefresh.ts
- src/hooks/common/useUser/useUser.ts
- src/libs/api/queryClient.ts
- src/pages/_app.tsx
- yarn.lock
- 기존 `react-query@3.x.x`에서 `@tanstack/react-query@4.x.x`로 대응했어요
- 가장 크게 대응한 사항은 `QueryKey` 부분이에요
- 기존에는 string type도 가능했는데, 이제는 `unknown[]` 타입이더라구요 https://tanstack.com/query/v4/docs/guides/query-keys
- `@tanstack/react-query-devtools`도 패키지가 나누어졌더라구요. 
- 나머지는 import 네이밍만 바꿔 대응했어요
closes #477
> @tanstack/react-query 대응

- src/components/inspiration/InspirationTime.tsx
날짜 분기를 `-`에서 `/`로 변경했습니다.
- `2022-03-16 00:00:00`의 형태의 날짜 new date할 경우 에러 발생합니다.
https://2dowon.github.io/docs/javascript/ios-new-date/
> safair 날짜 NaN 이슈

- src/pages/my/tag/index.tsx
- 태그 관리의 태그 등록 버튼의 위치를 margin을 이용해서 변경했습니다.
closed #515 
x
x
> fix: 태그 관리 - 태그등록 버튼 위치 변경

- src/components/home/FilterBottomSheetModal/CalendarFilterSection.tsx
- src/components/home/FilterBottomSheetModal/FilterBottomSheetModal.tsx
- src/components/home/FilterBottomSheetModal/TagFilterSection.tsx
- src/components/home/HomeNavigationBar.tsx
- src/pages/tag/index.tsx
수집이 필요한 이벤트를 부착했어요
- 네비게이션 필터 아이콘 버튼 클릭
- 필터링 바텀 시트의 `태그`, `기간` 클릭
- 필터링 바텀 시트의 CTA 버튼 클릭
- 태그 필터 완료 버튼 클릭
> 필터링 이벤트 부착

- .github/workflows/CI.yml
- .github/workflows/codeql.yml
- 워크플로우들의 트리거 브랜치를 조정했어요 ! `main`, `develop`, `test`
> ci 트리거 브랜치 변경

- package.json
> chore: package version to v1.1.1

- .vscode/settings.json
제가 아맞다 하면서 맛봤는데 엄청 달콤합니다!
임포트 순서 린트 오류 같은거 저장만 하면 바로 정렬돼버려가지고 ...
> 저장 시 포매팅 적용

- src/components/common/LoadingHandler/LoadingHandler.test.tsx
- src/components/common/LoadingHandler/index.test.tsx
- `LoadingHandler` 테스트 코드를 작성했어요~
> loading handler 테스트

- src/hooks/analytics/useRecordPageview.ts
기존 이벤트 기록 유틸에서는 버전이 기록되고 있었는데, 페이지뷰에서는 안되고 있더라구요
페이지뷰에서도 버전과 함께 기록되도록 했습니당
close #563
> 페이지뷰 이벤트에 버전 기록

- @types/global.d.ts
- src/components/common/UserProvider/UserProvider.tsx
- src/hooks/api/member/useGetUserInformation.ts
- src/hooks/common/useUser/useUser.ts
- src/libs/mixpanel/index.test.ts
- src/libs/mixpanel/index.ts
- src/libs/mixpanel/mixpanel.test.ts
- src/libs/mixpanel/mixpanel.ts
- src/pages/login/index.tsx
공식문서에서 안내하는 것처럼 `mixpanel.identify`를 사용했어요
유저가 로그인 될 시 적용하기 위해 `useUser`의 로그인 유틸에 추가했어요
> 사용자 정보와 함께 기록하는 것이 확인에 유리할 것 같아 사용자 정보를 받은 후 사용해요
close #562
> 믹스패널 유저 identify 호출

- src/styles/GlobalStyle/GlobalStyle.tsx
- src/styles/GlobalStyle/reset.ts
안녕하세요 👋 , 
지인의 소개로 알게된 오픈소스 프로젝트를 둘러보다가 회원가입 도중 정렬이 안 맞는 내용이 있어 확인 중에 개선할 수 있어보이는 사항이 있어 이렇게 PR을 생성하게 되었습니다.
너무 좋은 프로젝트를 이렇게 오픈소스로 볼 수 있어서 영광이었고, 많이 배웠습니다.
이번 기회를 통해 영감탱에 더 많은 기여를 할 수 있는 기회가 되었으면 좋겠습니다.
감사합니다.
svg 태그와 img 태그에 글로벌 css를 추가해주어 정렬 이슈를 해결했습니다.
글로벌로 적용해도 무방할 것으로 보여 Global.tsx에 추가했습니다.
AS-IS
TO-BE
정렬이 안 맞던 기존 퍼블리싱
변경 후
https://www.daleseo.com/css-img-extra-space/
> svg, img vertical-align 추가

- CONTRIBUTING.md
컨트리뷰팅 가이드를 작성했어요
https://github.com/depromeet/ygtang-client/blob/docs/contributing/CONTRIBUTING.md
https://github.com/github/docs/blob/main/CONTRIBUTING.md
> 컨트리뷰팅 가이드 작성

- src/components/common/Tag/Tag.tsx
- src/components/common/TagForm/RegisteredTagList.tsx
- src/components/common/TagForm/TagForm.tsx
- src/remotes/tag.d.ts
- 태그 등록(편집, 필터)에서 서버로부터 오는 태그의 사용된 횟수를 보여주도록합니다.
- 태그 등록(편집, 필터)에서 선택된 태그에 border로 하이라이팅을 해줍니다.
closed #584
> 태그 폼 - 태그로 저장된 갯수 보여주기 

- src/components/home/ThumbnailContent.tsx
링크 영감중 사진이 없거나 사진을 불로올 수 없는 경우, 기본 이미지를 보여주도록 합니다.
*이미지는 디자이너분들의 요청에따라 변경될 수 있습니다.*
AS-IS
TO-BE
closed #577
> 링크 영감 기본 이미지 설정 

- README.md
> docs: 수상 텍스트 추가

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
@positiveko 님을 CODEOWNERS와 PR 리뷰 양식에서 제거합니다. 리뷰 알림 매번 보내드리는 것 같아 제거했습니다.
> codeowners에서 positiveko님 제거
